# Content autogenerated. Data from digimoncardgame.fandom.com

static func register_cards():

	CardDB.register_booster("BT-08", "BT-08: New Hero")
	CardDB.add_card(BT8_001.new())
	CardDB.add_card(BT8_002.new())
	CardDB.add_card(BT8_003.new())
	CardDB.add_card(BT8_004.new())
	CardDB.add_card(BT8_005.new())
	CardDB.add_card(BT8_006.new())
	CardDB.add_card(BT8_007.new())
	CardDB.add_card(BT8_008.new())
	CardDB.add_card(BT8_008_B.new())
	CardDB.add_card(BT8_009.new())
	CardDB.add_card(BT8_009_B.new())
	CardDB.add_card(BT8_010.new())
	CardDB.add_card(BT8_011.new())
	CardDB.add_card(BT8_012.new())
	CardDB.add_card(BT8_012_B.new())
	CardDB.add_card(BT8_013.new())
	CardDB.add_card(BT8_014.new())
	CardDB.add_card(BT8_015.new())
	CardDB.add_card(BT8_016.new())
	CardDB.add_card(BT8_017.new())
	CardDB.add_card(BT8_018.new())
	CardDB.add_card(BT8_019.new())
	CardDB.add_card(BT8_020.new())
	CardDB.add_card(BT8_021.new())
	CardDB.add_card(BT8_022.new())
	CardDB.add_card(BT8_023.new())
	CardDB.add_card(BT8_024.new())
	CardDB.add_card(BT8_025.new())
	CardDB.add_card(BT8_026.new())
	CardDB.add_card(BT8_026_B.new())
	CardDB.add_card(BT8_027.new())
	CardDB.add_card(BT8_028.new())
	CardDB.add_card(BT8_029.new())
	CardDB.add_card(BT8_030.new())
	CardDB.add_card(BT8_031.new())
	CardDB.add_card(BT8_032.new())
	CardDB.add_card(BT8_032_B.new())
	CardDB.add_card(BT8_033.new())
	CardDB.add_card(BT8_033_B.new())
	CardDB.add_card(BT8_034.new())
	CardDB.add_card(BT8_035.new())
	CardDB.add_card(BT8_036.new())
	CardDB.add_card(BT8_037.new())
	CardDB.add_card(BT8_038.new())
	CardDB.add_card(BT8_038_B.new())
	CardDB.add_card(BT8_039.new())
	CardDB.add_card(BT8_039_B.new())
	CardDB.add_card(BT8_040.new())
	CardDB.add_card(BT8_041.new())
	CardDB.add_card(BT8_042.new())
	CardDB.add_card(BT8_043.new())
	CardDB.add_card(BT8_044.new())
	CardDB.add_card(BT8_045.new())
	CardDB.add_card(BT8_046.new())
	CardDB.add_card(BT8_047.new())
	CardDB.add_card(BT8_048.new())
	CardDB.add_card(BT8_049.new())
	CardDB.add_card(BT8_050.new())
	CardDB.add_card(BT8_051.new())
	CardDB.add_card(BT8_051_B.new())
	CardDB.add_card(BT8_052.new())
	CardDB.add_card(BT8_053.new())
	CardDB.add_card(BT8_054.new())
	CardDB.add_card(BT8_055.new())
	CardDB.add_card(BT8_056.new())
	CardDB.add_card(BT8_057.new())
	CardDB.add_card(BT8_057_B.new())
	CardDB.add_card(BT8_058.new())
	CardDB.add_card(BT8_059.new())
	CardDB.add_card(BT8_060.new())
	CardDB.add_card(BT8_060_B.new())
	CardDB.add_card(BT8_061.new())
	CardDB.add_card(BT8_062.new())
	CardDB.add_card(BT8_063.new())
	CardDB.add_card(BT8_064.new())
	CardDB.add_card(BT8_065.new())
	CardDB.add_card(BT8_066.new())
	CardDB.add_card(BT8_067.new())
	CardDB.add_card(BT8_068.new())
	CardDB.add_card(BT8_069.new())
	CardDB.add_card(BT8_069_B.new())
	CardDB.add_card(BT8_070.new())
	CardDB.add_card(BT8_070_B.new())
	CardDB.add_card(BT8_071.new())
	CardDB.add_card(BT8_072.new())
	CardDB.add_card(BT8_073.new())
	CardDB.add_card(BT8_074.new())
	CardDB.add_card(BT8_075.new())
	CardDB.add_card(BT8_076.new())
	CardDB.add_card(BT8_077.new())
	CardDB.add_card(BT8_078.new())
	CardDB.add_card(BT8_079.new())
	CardDB.add_card(BT8_080.new())
	CardDB.add_card(BT8_081.new())
	CardDB.add_card(BT8_082.new())
	CardDB.add_card(BT8_082_B.new())
	CardDB.add_card(BT8_083.new())
	CardDB.add_card(BT8_083_B.new())
	CardDB.add_card(BT8_084.new())
	CardDB.add_card(BT8_084_B.new())
	CardDB.add_card(BT8_085.new())
	CardDB.add_card(BT8_085_B.new())
	CardDB.add_card(BT8_086.new())
	CardDB.add_card(BT8_087.new())
	CardDB.add_card(BT8_087_B.new())
	CardDB.add_card(BT8_088.new())
	CardDB.add_card(BT8_088_B.new())
	CardDB.add_card(BT8_089.new())
	CardDB.add_card(BT8_089_B.new())
	CardDB.add_card(BT8_090.new())
	CardDB.add_card(BT8_090_B.new())
	CardDB.add_card(BT8_091.new())
	CardDB.add_card(BT8_092.new())
	CardDB.add_card(BT8_093.new())
	CardDB.add_card(BT8_094.new())
	CardDB.add_card(BT8_095.new())
	CardDB.add_card(BT8_096.new())
	CardDB.add_card(BT8_097.new())
	CardDB.add_card(BT8_098.new())
	CardDB.add_card(BT8_099.new())
	CardDB.add_card(BT8_100.new())
	CardDB.add_card(BT8_101.new())
	CardDB.add_card(BT8_102.new())
	CardDB.add_card(BT8_103.new())
	CardDB.add_card(BT8_104.new())
	CardDB.add_card(BT8_105.new())
	CardDB.add_card(BT8_106.new())
	CardDB.add_card(BT8_107.new())
	CardDB.add_card(BT8_108.new())
	CardDB.add_card(BT8_109.new())
	CardDB.add_card(BT8_110.new())
	CardDB.add_card(BT8_111.new())
	CardDB.add_card(BT8_111_B.new())
	CardDB.add_card(BT8_112.new())
	CardDB.add_card(BT8_112_B.new())

class BT8_001 extends Card:
	func _init():
		name = "Gurimon"
		type = Type.DIGITAMA
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT8-001"
		level = 2
		stage_level = Stage.IN_TRAINING
		digimon_type = "Lesser"
		inherited_effect_text = "[When Attacking] [Once Per Turn] If this Digimon has 6000 DP or more, [Draw 1]."

class BT8_002 extends Card:
	func _init():
		name = "Hiyarimon"
		type = Type.DIGITAMA
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "BT8-002"
		level = 2
		stage_level = Stage.IN_TRAINING
		digimon_type = "Lesser"
		inherited_effect_text = "[All Turns] While your opponent has no Digimon with digivolution cards, this Digimon gets +1000 DP."

class BT8_003 extends Card:
	func _init():
		name = "Frimon"
		type = Type.DIGITAMA
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT8-003"
		level = 2
		stage_level = Stage.IN_TRAINING
		digimon_type = "Lesser"
		inherited_effect_text = "[Your Turn] While you have 3 or more security cards, this Digimon gets +1000 DP."

class BT8_004 extends Card:
	func _init():
		name = "Bibimon"
		type = Type.DIGITAMA
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "BT8-004"
		level = 2
		stage_level = Stage.IN_TRAINING
		digimon_type = "Lesser"
		inherited_effect_text = "[Opponent Turn] While all of your Digimon are suspended, this Digimon gets +1000 DP."

class BT8_005 extends Card:
	func _init():
		name = "Kyokyomon"
		type = Type.DIGITAMA
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "BT8-005"
		level = 2
		stage_level = Stage.IN_TRAINING
		digimon_type = "Lesser"
		inherited_effect_text = "[Your Turn] [Once Per Turn] When an effect places a digivolution card under this Digimon, it gets +1000 DP until the end of your opponent's next turn."

class BT8_006 extends Card:
	func _init():
		name = "DemiMeramon"
		type = Type.DIGITAMA
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT8-006"
		level = 2
		stage_level = Stage.IN_TRAINING
		digimon_type = "Lesser"
		inherited_effect_text = "[Your Turn] [Once Per Turn] When a card is trashed from your deck, [Draw 1]."

class BT8_007 extends Card:
	func _init():
		name = "Gazimon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT8-007"
		play_cost = 2
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.RED
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Mammal"
		power = 3000

class BT8_008 extends Card:
	func _init():
		name = "Gammamon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT8-008"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.RED
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Ceratopsian"
		power = 2000
		effect_text = "[Your Turn] [Once Per Turn] When you play a red Tamer, [Draw 1]."
		inherited_effect_text = "[When Attacking] If this Digimon has 6000 DP or more, delete 1 of your opponent's Digimon with 3000 DP or less."

class BT8_008_B extends Card:
	func _init():
		name = "Gammamon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT8-008 (B)"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.RED
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Ceratopsian"
		power = 2000
		effect_text = "[Your Turn] [Once Per Turn] When you play a red Tamer, [Draw 1]."
		inherited_effect_text = "[When Attacking] If this Digimon has 6000 DP or more, delete 1 of your opponent's Digimon with 3000 DP or less."
		is_parallel = true
		notes = "parallel promo"

class BT8_009 extends Card:
	func _init():
		name = "Hawkmon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT8-009"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Avian"
		power = 2000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 2-color red card among them to your hand. Place the remaining cards at the bottom of your deck in any order."

class BT8_009_B extends Card:
	func _init():
		name = "Hawkmon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT8-009 (B)"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Avian"
		power = 2000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 2-color red card among them to your hand. Place the remaining cards at the bottom of your deck in any order."
		is_parallel = true
		notes = "parallel promo"

class BT8_010 extends Card:
	func _init():
		name = "Aquilamon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT8-010"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Giant Bird"
		power = 4000
		effect_text = "When playing this card from your hand, reduce its play cost by 1 if you have a yellow Digimon in play."
		inherited_effect_text = "[When Attacking] If you have a yellow Digimon in play, delete 1 of your opponent's Digimon with 5000 DP or less."

class BT8_011 extends Card:
	func _init():
		name = "Cyclonemon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT8-011"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.RED
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.BLACK
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Dragonkin"
		power = 5000
		inherited_effect_text = "[When Attacking] Delete 1 of your opponent's Digimon with 2000 DP or less."
		notes = "Cyclomon"

class BT8_012 extends Card:
	func _init():
		name = "Flamedramon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT8-012"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 3
		digimon_type = "Dragonkin"
		power = 5000
		effect_text = "Digivolve from [Veemon] for [2] cost[Armor Release].\n[When Attacking] This Digimon gets +3000 DP for the turn."
		notes = "Fladramon"

class BT8_012_B extends Card:
	func _init():
		name = "Flamedramon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT8-012 (B)"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 3
		digimon_type = "Dragonkin"
		power = 5000
		effect_text = "Digivolve from [Veemon] for [2] cost[Armor Release].\n[When Attacking] This Digimon gets +3000 DP for the turn."
		is_parallel = true
		notes = "parallel promo Fladramon"

class BT8_013 extends Card:
	func _init():
		name = "BetelGammamon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT8-013"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.RED
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Dragonkin"
		power = 6000
		effect_text = "[When Digivolved] [Blitz]."

class BT8_014 extends Card:
	func _init():
		name = "SkullMeramon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT8-014"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.RED
		digivolve_cost = 2
		digivolve_level = 4
		digimon_type = "Flame"
		power = 7000

class BT8_015 extends Card:
	func _init():
		name = "Silphymon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT8-015"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 4
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 4
		digivolve_level_2 = 4
		digimon_type = "Beastkin"
		power = 8000
		effect_text = "<DNA Digivolve: [Red] + [4|Yellow|4]: [0]>\n[When Digivolved] 1 of your opponent's Digimon gets -5000 DP for the turn. Then, when DNA digivolving, delete 1 of your opponent's Digimon with 5000 DP or less."
		inherited_effect_text = "[When Attacking] Delete 1 of your opponent's Digimon with 5000 DP or less."

class BT8_016 extends Card:
	func _init():
		name = "MasterTyrannomon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT8-016"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 4
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 4
		digivolve_level_2 = 4
		digimon_type = "Dinosaur"
		power = 8000
		effect_text = "[Your Turn] All of your Digimon with Tyrannomon, text=in their name gain [Security Attack +1]."
		inherited_effect_text = "[Security Attack +1]."

class BT8_017 extends Card:
	func _init():
		name = "UltimateBrachiomon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT8-017"
		play_cost = 10
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.BLACK
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Cyborg"
		power = 13000
		notes = "UltimateBrachimon"

class BT8_018 extends Card:
	func _init():
		name = "Marsmon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT8-018"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Shaman"
		power = 11000
		effect_text = "[Your Turn] This Digimon can also attack your opponent's unsuspended Digimon."

class BT8_019 extends Card:
	func _init():
		name = "Zhuqiaomon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.SR
		id = "BT8-019"
		play_cost = 13
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.RED
		digivolve_cost = 5
		digivolve_level = 5
		digimon_type = "Holy Bird"
		power = 13000
		effect_text = "[When Digivolved] Your opponent chooses 1 of their Digimon. Delete all Digimon other than this Digimon and your opponent's chosen Digimon. For each Digimon deleted by this effect, gain 1 memory.\n[Your Turn] When an opponent's Digimon is deleted, this Digimon gains [Security Attack +1] for the turn for each of your opponent's Digimon deleted."

class BT8_020 extends Card:
	func _init():
		name = "Patamon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT8-020"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Mammal"
		power = 3000
		inherited_effect_text = "[End of Your Turn] You may DNA digivolve this Digimon and one of your other Digimon in play into a Digimon card in your hand by paying its DNA digivolve cost."

class BT8_021 extends Card:
	func _init():
		name = "Veemon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "BT8-021"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Mini Dragon"
		power = 2000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 2-color blue card among them to your hand. Place the remaining cards at the bottom of your deck in any order."
		notes = "V-mon"

class BT8_022 extends Card:
	func _init():
		name = "SnowAgumon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT8-022"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digimon_type = "Dinosaur"
		power = 2000
		effect_text = "[On Play] Trash the top digivolution card of 1 of your opponent's Digimon."
		notes = "YukiAgumon"

class BT8_023 extends Card:
	func _init():
		name = "Submarimon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "BT8-023"
		play_cost = 4
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 3
		digimon_type = "Sea Animal"
		power = 4000
		effect_text = "Digivolve from [Armadillomon] for [2] cost[Armor Release].\n[When Digivolved] Trash the bottom digivolution card of 1 of your opponent's Digimon. Then, 1 of your opponent's Digimon with no digivolution cards gets -3000 DP for the turn."

class BT8_024 extends Card:
	func _init():
		name = "Angemon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT8-024"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 3
		digivolve_level_2 = 3
		digimon_type = "Angel"
		power = 6000
		effect_text = "[Your Turn] When this Digimon would digivolve, if you have 3 or fewer security cards, [Recovery +1]."
		inherited_effect_text = "[When Attacking] If you have 3 or more security cards, return 1 of your opponent's level 3 Digimon to its owner's hand."

class BT8_025 extends Card:
	func _init():
		name = "Hookmon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT8-025"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.BLACK
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Mutant"
		power = 5000
		inherited_effect_text = "[When Attacking] Trash the bottom digivolution card of 1 of your opponent's Digimon."

class BT8_026 extends Card:
	func _init():
		name = "Halsemon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT8-026"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 3
		digimon_type = "Beast"
		power = 5000
		effect_text = "Digivolve from [Hawkmon] for [2] cost[Armor Release].\n[When Attacking] Delete 1 of your opponent's level 3 Digimon."

class BT8_026_B extends Card:
	func _init():
		name = "Halsemon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT8-026 (B)"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 3
		digimon_type = "Beast"
		power = 5000
		effect_text = "Digivolve from [Hawkmon] for [2] cost[Armor Release].\n[When Attacking] Delete 1 of your opponent's level 3 Digimon."
		is_parallel = true
		notes = "parallel promo"

class BT8_027 extends Card:
	func _init():
		name = "Scorpiomon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT8-027"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 4
		digimon_type = "Crustacean"
		power = 8000
		notes = "Anomalocarimon"

class BT8_028 extends Card:
	func _init():
		name = "CaptainHookmon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT8-028"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Marine Man"
		power = 7000
		effect_text = "[All Turns] When your opponent plays a level 5 or higher Digimon, gain 1 memory and [Draw 1]."

class BT8_029 extends Card:
	func _init():
		name = "Frozomon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT8-029"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Machine"
		power = 7000
		effect_text = "[Blocker]\n[Your Turn] While your opponent has a Digimon with a digivolution card in play, this Digimon can't attack."
		inherited_effect_text = "[All Turns] [Once Per Turn] When a digivolution card of an opponent's Digimon is trashed, return 1 of your opponent's level 3 Digimon to its owner's hand."

class BT8_030 extends Card:
	func _init():
		name = "Surfimon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT8-030"
		play_cost = 10
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.BLACK
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Cyborg"
		power = 13000

class BT8_031 extends Card:
	func _init():
		name = "FrosVelgrmon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT8-031"
		play_cost = 11
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Giant Bird"
		power = 12000
		effect_text = "[When Digivolved] Trash the top digivolution card of 1 of your opponent's Digimon. Then, return 1 of your opponent's Digimon with no digivolution cards to its owner's hand.\n[Opponent Turn] All of your opponent's Digimon gain \"[When Attacking] Trash the bottom digivolution card of this Digimon.\""

class BT8_032 extends Card:
	func _init():
		name = "Imperialdramon Fighter Mode"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.SR
		id = "BT8-032"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 5
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 5
		digivolve_level_2 = 5
		digimon_type = "Ancient Dragonkin"
		power = 13000
		effect_text = "Digivolve from [Dragon Mode] for [2] cost[When Digivolved] Return 1 of your opponent's Digimon with 10000 DP or less to its owner's hand.\n[When Attacking] [Once Per Turn] If a blue card is in this Digimon's digivolution cards, unsuspend 1 of your Digimon. If a green card is in this Digimon's digivolution cards, suspend 1 of your opponent's Digimon."

class BT8_032_B extends Card:
	func _init():
		name = "Imperialdramon Fighter Mode"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.SR
		id = "BT8-032 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 5
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 5
		digivolve_level_2 = 5
		digimon_type = "Ancient Dragonkin"
		power = 13000
		effect_text = "Digivolve from [Dragon Mode] for [2] cost[When Digivolved] Return 1 of your opponent's Digimon with 10000 DP or less to its owner's hand.\n[When Attacking] [Once Per Turn] If a blue card is in this Digimon's digivolution cards, unsuspend 1 of your Digimon. If a green card is in this Digimon's digivolution cards, suspend 1 of your opponent's Digimon."
		is_parallel = true
		notes = "parallel promo"

class BT8_033 extends Card:
	func _init():
		name = "Armadillomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT8-033"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.BLUE
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Mammal"
		power = 2000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 2-color yellow card among them to your hand. Place the remaining cards at the bottom of your deck in any order."
		notes = "Armadimon"

class BT8_033_B extends Card:
	func _init():
		name = "Armadillomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT8-033 (B)"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.BLUE
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Mammal"
		power = 2000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 2-color yellow card among them to your hand. Place the remaining cards at the bottom of your deck in any order."
		is_parallel = true
		notes = "parallel promo Armadimon"

class BT8_034 extends Card:
	func _init():
		name = "Elecmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT8-034"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digimon_type = "Mammal"
		power = 4000

class BT8_035 extends Card:
	func _init():
		name = "Candlemon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT8-035"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.PURPLE
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Flame"
		power = 2000
		inherited_effect_text = "[Your Turn] [Once Per Turn] When you play another purple Digimon, gain 1 memory."
		notes = "Candmon"

class BT8_036 extends Card:
	func _init():
		name = "Ankylomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT8-036"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.BLUE
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Ankylosaur"
		power = 4000
		effect_text = "When playing this card from your hand, reduce its play cost by 1 if you have a blue Digimon in play."
		inherited_effect_text = "[When Attacking] If you have a blue Digimon in play, 1 of your opponent's Digimon gets -3000 DP for the turn."

class BT8_037 extends Card:
	func _init():
		name = "Dinohyumon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT8-037"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.RED
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Dragonkin"
		power = 5000
		inherited_effect_text = "[When Attacking] 1 of your opponent's Digimon gets -1000 DP for the turn."

class BT8_038 extends Card:
	func _init():
		name = "Magnamon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "BT8-038"
		play_cost = 7
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 4
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.BLUE
		digivolve_cost_2 = 4
		digivolve_level_2 = 3
		digimon_type = "Holy Warrior"
		power = 7000
		effect_text = "Digivolve from [Veemon] for [3] cost[Blocker].\n[Armor Release].\n[When Digivolved] Unsuspend this Digimon, and it gets +2000 DP until the end of your opponent's next turn for each card with [Armor Form] in your trash."

class BT8_038_B extends Card:
	func _init():
		name = "Magnamon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "BT8-038 (B)"
		play_cost = 7
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 4
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.BLUE
		digivolve_cost_2 = 4
		digivolve_level_2 = 3
		digimon_type = "Holy Warrior"
		power = 7000
		effect_text = "Digivolve from [Veemon] for [3] cost[Blocker].\n[Armor Release].\n[When Digivolved] Unsuspend this Digimon, and it gets +2000 DP until the end of your opponent's next turn for each card with [Armor Form] in your trash."
		is_parallel = true
		notes = "parallel promo"

class BT8_039 extends Card:
	func _init():
		name = "Rapidmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "BT8-039"
		play_cost = 6
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 4
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 4
		digivolve_level_2 = 3
		digimon_type = "Holy Warrior"
		power = 6000
		effect_text = "Digivolve from [Terriermon] for [3] cost[Armor Release].\n[When Digivolved] Suspend 1 of your opponent's Digimon for each Tamer you have in play. Then, up to 3 of your opponent's suspended Digimon get -5000 DP for the turn."

class BT8_039_B extends Card:
	func _init():
		name = "Rapidmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "BT8-039 (B)"
		play_cost = 6
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 4
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 4
		digivolve_level_2 = 3
		digimon_type = "Holy Warrior"
		power = 6000
		effect_text = "Digivolve from [Terriermon] for [3] cost[Armor Release].\n[When Digivolved] Suspend 1 of your opponent's Digimon for each Tamer you have in play. Then, up to 3 of your opponent's suspended Digimon get -5000 DP for the turn."
		is_parallel = true
		notes = "parallel promo"

class BT8_040 extends Card:
	func _init():
		name = "Betsumon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT8-040"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Puppet"
		power = 7000
		effect_text = "[When Digivolved] You may trash 1 card in your hand to treat this Digimon as also having the colors of the trashed card for the turn. Then, if this Digimon has 2 or more colors, [Draw 2]."

class BT8_041 extends Card:
	func _init():
		name = "Kyukimon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT8-041"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 3
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.PURPLE
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Mysterious Beast"
		power = 9000

class BT8_042 extends Card:
	func _init():
		name = "Shakkoumon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "BT8-042"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 4
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.BLUE
		digivolve_cost_2 = 4
		digivolve_level_2 = 4
		digimon_type = "Mutant"
		power = 8000
		effect_text = "<DNA Digivolve: [Yellow] + [4|Blue|4]: [0]>\n[When Digivolved] If you have 5 or fewer security cards, [Recovery +1]. Then, when DNA digivolving, return 1 of your opponent's Digimon whose level is less than or equal to the number of cards in your security stack to its owner's hand."
		inherited_effect_text = "[When Attacking] 1 of your opponent's Digimon gets -3000 DP for the turn."

class BT8_043 extends Card:
	func _init():
		name = "Cherubimon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT8-043"
		play_cost = 11
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 4
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.PURPLE
		digivolve_cost_2 = 4
		digivolve_level_2 = 5
		digimon_type = "Cherub"
		power = 12000
		effect_text = "When playing this card from your hand, you may delete 1 of your purple [Cherubimon] to reduce this card's play cost by 8.\n[On Play] [When Digivolved] For each Tamer you have in play, activate the effect below.\n·1 of your opponent's Digimon gets [Security Attack -2] until the end of your opponent's next turn."

class BT8_044 extends Card:
	func _init():
		name = "Azulongmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "BT8-044"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 3
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.BLUE
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Holy Dragon"
		power = 11000
		effect_text = "[When Attacking] You may trash the top card of your security stack to gain 2 memory.\n[Your Turn] [Once Per Turn] When one of your other Digimon digivolves, you may unsuspend it."
		notes = "Blue"

class BT8_045 extends Card:
	func _init():
		name = "Ekakimon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT8-045"
		play_cost = 2
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Mutant"
		power = 3000

class BT8_046 extends Card:
	func _init():
		name = "Terriermon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "BT8-046"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Beast"
		power = 2000
		effect_text = "[On Play] You may reveal the top 5 cards of your deck. Add 1 card with Gargomon, Rapidmon, text=in their name among them to your hand. Place the remaining cards at the bottom of your deck in any order."

class BT8_047 extends Card:
	func _init():
		name = "Pulsemon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT8-047"
		play_cost = 2
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Beastkin"
		power = 2000
		inherited_effect_text = "[All Turns] This Digimon gets +1000 DP for each of your other suspended Digimon."

class BT8_048 extends Card:
	func _init():
		name = "Shurimon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "BT8-048"
		play_cost = 4
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 3
		digimon_type = "Mutant"
		power = 4000
		effect_text = "Digivolve from [Hawkmon] for [2] cost[Armor Release].\n[When Digivolved] 1 of your opponent's Digimon with [Blocker] can't attack or block until the end of your opponent's next turn."

class BT8_049 extends Card:
	func _init():
		name = "Namakemon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "BT8-049"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Puppet"
		power = 3000
		effect_text = "[Main] You may suspend this Digimon to reveal the top 3 cards of your deck. Add 1 green Digimon card among them to your hand. Place the remaining cards at the bottom of your deck in any order."

class BT8_050 extends Card:
	func _init():
		name = "Exermon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT8-050"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Insectoid"
		power = 5000
		effect_text = "[When Digivolved] You may suspend 1 of your Digimon to suspend 1 of your opponent's Digimon."
		inherited_effect_text = "[All Turns] This Digimon gets +1000 DP for each of your other suspended Digimon."

class BT8_051 extends Card:
	func _init():
		name = "Digmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "BT8-051"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 3
		digimon_type = "Insectoid"
		power = 5000
		effect_text = "Digivolve from [Armadillomon] for [2] cost[Armor Release].\n[When Attacking] 1 of your opponent's suspended Digimon gets -3000 DP for the turn."

class BT8_051_B extends Card:
	func _init():
		name = "Digmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "BT8-051 (B)"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 3
		digimon_type = "Insectoid"
		power = 5000
		effect_text = "Digivolve from [Armadillomon] for [2] cost[Armor Release].\n[When Attacking] 1 of your opponent's suspended Digimon gets -3000 DP for the turn."
		is_parallel = true
		notes = "parallel promo"

class BT8_052 extends Card:
	func _init():
		name = "Drimogemon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT8-052"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 1
		digivolve_level = 3
		digimon_type = "Beast"
		power = 5000

class BT8_053 extends Card:
	func _init():
		name = "Lighdramon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.SR
		id = "BT8-053"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 3
		digimon_type = "Beast"
		power = 5000
		effect_text = "Digivolve from [Veemon] for [2] cost[Armor Release].\n[When Digivolved] Suspend 1 of your opponent's level 4 or lower Digimon."

class BT8_054 extends Card:
	func _init():
		name = "Pistmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT8-054"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Vegetation"
		power = 7000
		effect_text = "[Digisorption -2]."
		inherited_effect_text = "[All Turns] This Digimon gets +1000 DP for each of your other suspended Digimon."

class BT8_055 extends Card:
	func _init():
		name = "Climbmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "BT8-055"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digimon_type = "Insectoid"
		power = 8000
		effect_text = "[When Digivolved] If this Digimon is suspended, return 1 of your opponent's suspended Digimon with DP less than or equal to this Digimon's DP to its owner's hand."
		inherited_effect_text = "[Your Turn] When this Digimon becomes unsuspended during your unsuspend phase, suspend 1 of your opponent's Digimon."

class BT8_056 extends Card:
	func _init():
		name = "Spinomon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT8-056"
		play_cost = 10
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.RED
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Dinosaur"
		power = 13000

class BT8_057 extends Card:
	func _init():
		name = "Shivamon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.SR
		id = "BT8-057"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Insectoid"
		power = 12000
		effect_text = "[Opponent Turn] While all of your Digimon are suspended, your opponent can't use Option cards.\n[Your Turn] When this Digimon becomes unsuspended during your unsuspend phase, trash the top card of your opponent's security stack."

class BT8_057_B extends Card:
	func _init():
		name = "Shivamon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.SR
		id = "BT8-057 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Insectoid"
		power = 12000
		effect_text = "[Opponent Turn] While all of your Digimon are suspended, your opponent can't use Option cards.\n[Your Turn] When this Digimon becomes unsuspended during your unsuspend phase, trash the top card of your opponent's security stack."
		is_parallel = true
		notes = "parallel promo"

class BT8_058 extends Card:
	func _init():
		name = "Agumon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "BT8-058"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.RED
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Reptile"
		power = 2000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 card with Greymon and 1 card with [Dragonkin] among them to your hand. Place the remaining cards at the bottom of your deck in any order."

class BT8_059 extends Card:
	func _init():
		name = "Kokuwamon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT8-059"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Machine"
		power = 3000
		effect_text = "[All Turns] Players can't ignore digivolution requirements."

class BT8_060 extends Card:
	func _init():
		name = "Ryudamon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "BT8-060"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Beast"
		power = 1000
		effect_text = "[On Play] Reveal the top 3 cards of your deck. Add 1 card with [X-Antibody] and 1 [Yuji Musha] among them to your hand. Place the remaining cards at the bottom of your deck in any order."
		inherited_effect_text = "[All Turns] While this Digimon has [X-Antibody], it gains [Decoy]."

class BT8_060_B extends Card:
	func _init():
		name = "Ryudamon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "BT8-060 (B)"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Beast"
		power = 1000
		effect_text = "[On Play] Reveal the top 3 cards of your deck. Add 1 card with [X-Antibody] and 1 [Yuji Musha] among them to your hand. Place the remaining cards at the bottom of your deck in any order."
		inherited_effect_text = "[All Turns] While this Digimon has [X-Antibody], it gains [Decoy]."
		is_parallel = true
		notes = "parallel promo"

class BT8_061 extends Card:
	func _init():
		name = "Thundermon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT8-061"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Mutant"
		power = 6000
		effect_text = "The name of this card/Digimon is also treated as [Mamemon]."

class BT8_062 extends Card:
	func _init():
		name = "SkullKnightmon: Cavalier Mode"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "BT8-062"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.BLACK
		digivolve_cost_2 = 1
		digivolve_level_2 = 4
		digimon_type = "Enhancement"
		power = 5000
		effect_text = "The name of this card/Digimon is also treated as [SkullKnightmon] and [DeadlyAxemon].\n[When Digivolved] This Digimon gains [Jamming] and [Blocker] until the end of your opponent's next turn."

class BT8_063 extends Card:
	func _init():
		name = "Ginryumon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT8-063"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 3
		digimon_type = "Beast Dragon"
		power = 6000
		inherited_effect_text = "[Opponent Turn] While this Digimon has [X-Antibody], it gains [Blocker]."

class BT8_064 extends Card:
	func _init():
		name = "Greymon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT8-064"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.RED
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Dinosaur"
		power = 6000
		inherited_effect_text = "[Opponent Turn] While you have a red Digimon in play, this Digimon gains [Blocker]."

class BT8_065 extends Card:
	func _init():
		name = "CatchMamemon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT8-065"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Mutant"
		power = 7000
		effect_text = "[When Digivolved] You may return up to 4 Digimon cards with Mamemon, text=in their name from your hand and/or trash to the top of your deck in any order. If you return 3 or more cards using this effect, [De-Digivolve 1]."

class BT8_066 extends Card:
	func _init():
		name = "Hisyaryumon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT8-066"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Beast Dragon"
		power = 8000
		effect_text = "[Your Turn] When one of your effects places a digivolution card under this Digimon, you may digivolve this Digimon into a Digimon card in your hand with [X-Antibody] by paying its digivolution cost. When digivolving with this effect, reduce the digivolution cost by 1."
		inherited_effect_text = "[Opponent Turn] While this Digimon has [X-Antibody], it gains [Reboot]."

class BT8_067 extends Card:
	func _init():
		name = "MetalGreymon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "BT8-067"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 4
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.RED
		digivolve_cost_2 = 4
		digivolve_level_2 = 4
		digimon_type = "Cyborg"
		power = 8000
		effect_text = "[When Digivolved] [De-Digivolve 1]. Then, delete 1 of your opponent's Digimon with 3000 DP or less."
		inherited_effect_text = "[Your Turn] While this Digimon has [Dragonkin], it can also attack your opponent's unsuspended Digimon."

class BT8_068 extends Card:
	func _init():
		name = "BanchoMamemon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "BT8-068"
		play_cost = 11
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Mutant"
		power = 11000
		effect_text = "[When Digivolved] You may reveal the top 3 cards of your deck. For each of your opponent's Digimon, you may play 1 Digimon card with Mamemon and a memory cost of 10 or less among the revealed cards without paying its memory cost. Trash the remaining cards.\n[All Turns] While you have another Digimon with Mamemon in play, this Digimon gains [Security Attack +1]."

class BT8_069 extends Card:
	func _init():
		name = "Ouryumon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.SR
		id = "BT8-069"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Beast Dragon"
		power = 12000
		effect_text = "[When Digivolved] You may place 1 card with [X-Antibody] from your hand under this Digimon as its bottom digivolution card to delete 1 of your opponent's Digimon with a play cost of 7 or less.\n[Your Turn] [Once Per Turn] When one of your effects places a digivolution card under your Digimon, this Digimon gets +2000 DP and can't be deleted by your opponent's effects until the end of your opponent's next turn."
		inherited_effect_text = "[End of Attack] [Once Per Turn] If this Digimon has Alphamon, unsuspend it."

class BT8_069_B extends Card:
	func _init():
		name = "Ouryumon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.SR
		id = "BT8-069 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Beast Dragon"
		power = 12000
		effect_text = "[When Digivolved] You may place 1 card with [X-Antibody] from your hand under this Digimon as its bottom digivolution card to delete 1 of your opponent's Digimon with a play cost of 7 or less.\n[Your Turn] [Once Per Turn] When one of your effects places a digivolution card under your Digimon, this Digimon gets +2000 DP and can't be deleted by your opponent's effects until the end of your opponent's next turn."
		inherited_effect_text = "[End of Attack] [Once Per Turn] If this Digimon has Alphamon, unsuspend it."
		is_parallel = true
		notes = "parallel promo"

class BT8_070 extends Card:
	func _init():
		name = "BlackWarGreymon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.SR
		id = "BT8-070"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 4
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.RED
		digivolve_cost_2 = 4
		digivolve_level_2 = 5
		digimon_type = "Dragonkin"
		power = 12000
		effect_text = "[When Digivolved] If this Digimon has a red digivolution card, choose any number of your opponent's Digimon. If this Digimon has a black digivolution card, choose any number of your opponent's Tamers. The chosen cards' play costs must add up to 6 or less. Delete the chosen cards.\n[All Turns] [Once Per Turn] When an opponent's Digimon is deleted, unsuspend this Digimon."

class BT8_070_B extends Card:
	func _init():
		name = "BlackWarGreymon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.SR
		id = "BT8-070 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 4
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.RED
		digivolve_cost_2 = 4
		digivolve_level_2 = 5
		digimon_type = "Dragonkin"
		power = 12000
		effect_text = "[When Digivolved] If this Digimon has a red digivolution card, choose any number of your opponent's Digimon. If this Digimon has a black digivolution card, choose any number of your opponent's Tamers. The chosen cards' play costs must add up to 6 or less. Delete the chosen cards.\n[All Turns] [Once Per Turn] When an opponent's Digimon is deleted, unsuspend this Digimon."
		is_parallel = true
		notes = "parallel promo"

class BT8_071 extends Card:
	func _init():
		name = "Psychemon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT8-071"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Mutant"
		power = 3000
		effect_text = "[All Turns] Players can't reduce play costs."

class BT8_072 extends Card:
	func _init():
		name = "DemiDevimon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT8-072"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Evil"
		power = 2000
		effect_text = "[On Play] Reveal the top 3 cards of your deck. Add 1 Tamer card among them to your hand, and trash 1 purple Digimon card among them. Place the remaining cards at the bottom of your deck in any order."

class BT8_073 extends Card:
	func _init():
		name = "Mushroomon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT8-073"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Vegetation"
		power = 4000

class BT8_074 extends Card:
	func _init():
		name = "Soulmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT8-074"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Ghost"
		power = 4000
		inherited_effect_text = "[Your Turn] [Once Per Turn] When a card is trashed from your deck, gain 1 memory."

class BT8_075 extends Card:
	func _init():
		name = "Kogamon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT8-075"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Mutant"
		power = 4000
		inherited_effect_text = "[Retaliation]."

class BT8_076 extends Card:
	func _init():
		name = "Fangmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT8-076"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Dark Animal"
		power = 4000
		effect_text = "[Retaliation]."

class BT8_077 extends Card:
	func _init():
		name = "BlackGatomon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT8-077"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 3
		digivolve_level_2 = 3
		digimon_type = "Dark Animal"
		power = 6000
		effect_text = "[Rush]."
		inherited_effect_text = "[Retaliation]."
		notes = "BlackTailmon"

class BT8_078 extends Card:
	func _init():
		name = "Karatenmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT8-078"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 2
		digivolve_level = 4
		digimon_type = "Wizard"
		power = 7000

class BT8_079 extends Card:
	func _init():
		name = "SkullSatamon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT8-079"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Undead"
		power = 7000
		effect_text = "[When Digivolved] Trash the top 2 cards of your deck. Then, return 1 card with [Demon Lord] from your trash to your hand."
		inherited_effect_text = "[Your Turn] [Once Per Turn] When a card is trashed from your deck, gain 1 memory."

class BT8_080 extends Card:
	func _init():
		name = "Myotismon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.R
		id = "BT8-080"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Wizard"
		power = 8000
		effect_text = "[When Digivolved] Trash the top 2 cards of your deck. Then, you may play 1 [Yukio Oikawa] from your trash without paying its memory cost."
		inherited_effect_text = "[On Deletion] If this Digimon has Myotismon, you may play 1 [Yukio Oikawa] from your hand or trash suspended without paying its memory cost."
		notes = "Vamdemon"

class BT8_081 extends Card:
	func _init():
		name = "Rasenmon: Fury Mode"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT8-081"
		play_cost = 11
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Mysterious Beast"
		power = 13000
		effect_text = "[End of Attack] You may digivolve this Digimon into a [Rasenmon] in your hand without paying its memory cost, ignoring its digivolution requirements.\n[End of Your Turn] Trash the top card of your security stack."
		inherited_effect_text = "[Your Turn] When this card is trashed as a digivolution card by the effect of [Rasenmon], unsuspend 1 of your Digimon and it gets +3000 DP for the turn."

class BT8_082 extends Card:
	func _init():
		name = "Ophanimon: Falldown Mode"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.SR
		id = "BT8-082"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 4
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 4
		digivolve_level_2 = 5
		digimon_type = "Fallen Angel"
		power = 12000
		effect_text = "Digivolve from [Ophanimon] for [2] cost[When Digivolved] If this Digimon has a purple card in its digivolution cards, delete 1 of your opponent's level 4 or lower Digimon. If this Digimon has a yellow card in its digivolution cards, [Recovery +1].\n[On Deletion] You may play 1 purple or yellow level 4 or lower Digimon card from your trash without paying its memory cost."

class BT8_082_B extends Card:
	func _init():
		name = "Ophanimon: Falldown Mode"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.SR
		id = "BT8-082 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 4
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 4
		digivolve_level_2 = 5
		digimon_type = "Fallen Angel"
		power = 12000
		effect_text = "Digivolve from [Ophanimon] for [2] cost[When Digivolved] If this Digimon has a purple card in its digivolution cards, delete 1 of your opponent's level 4 or lower Digimon. If this Digimon has a yellow card in its digivolution cards, [Recovery +1].\n[On Deletion] You may play 1 purple or yellow level 4 or lower Digimon card from your trash without paying its memory cost."
		is_parallel = true
		notes = "parallel promo"

class BT8_083 extends Card:
	func _init():
		name = "MaloMyotismon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.SR
		id = "BT8-083"
		play_cost = 13
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Demon Lord"
		power = 12000
		effect_text = "[On Play] If there are 5 or more cards with Myotismon, text=in their names in your trash, delete 1 of your opponent's unsuspended Digimon and trash the top card of your opponent's security stack.\n[When Digivolved] Trash the top 5 cards of your deck. Then, if there's a card with Myotismon in your trash, gain 1 memory."
		notes = "BelialVamdemon"

class BT8_083_B extends Card:
	func _init():
		name = "MaloMyotismon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.SR
		id = "BT8-083 (B)"
		play_cost = 13
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Demon Lord"
		power = 12000
		effect_text = "[On Play] If there are 5 or more cards with Myotismon, text=in their names in your trash, delete 1 of your opponent's unsuspended Digimon and trash the top card of your opponent's security stack.\n[When Digivolved] Trash the top 5 cards of your deck. Then, if there's a card with Myotismon in your trash, gain 1 memory."
		is_parallel = true
		notes = "parallel promo BelialVamdemon"

class BT8_084 extends Card:
	func _init():
		name = "Kimeramon"
		type = Type.DIGIMON
		color = ColorGroup.WHITE
		rarity = Rarity.SR
		id = "BT8-084"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.DATA
		digivolve_color = ""
		digivolve_cost = 4
		digivolve_level = 4
		digimon_type = "Composite"
		power = 8000
		effect_text = "<DNA Digivolve: [|4] + [|4]: [0]>\n[When Digivolved] You may place 1 level 5 or lower Digimon card from your trash under this Digimon as its bottom digivolution card. Then, up to 4 of your opponent's Digimon get -1000 DP for each of this Digimon's colors until the end of your opponent's next turn.\n[Your Turn] This Digimon is treated as also having the colors of its digivolution cards. While this Digimon has 4 or more colors, it gets +4000 DP."

class BT8_084_B extends Card:
	func _init():
		name = "Kimeramon"
		type = Type.DIGIMON
		color = ColorGroup.WHITE
		rarity = Rarity.SR
		id = "BT8-084 (B)"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.DATA
		digivolve_color = ""
		digivolve_cost = 4
		digivolve_level = 4
		digimon_type = "Composite"
		power = 8000
		effect_text = "<DNA Digivolve: [|4] + [|4]: [0]>\n[When Digivolved] You may place 1 level 5 or lower Digimon card from your trash under this Digimon as its bottom digivolution card. Then, up to 4 of your opponent's Digimon get -1000 DP for each of this Digimon's colors until the end of your opponent's next turn.\n[Your Turn] This Digimon is treated as also having the colors of its digivolution cards. While this Digimon has 4 or more colors, it gets +4000 DP."
		is_parallel = true
		notes = "parallel promo"

class BT8_085 extends Card:
	func _init():
		name = "Yolei Inoue"
		type = Type.TAMER
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT8-085"
		play_cost = 3
		effect_text = "[Start of Your Main Phase] If you have a red Digimon in play, gain 1 memory.\n[Your Turn] When one of your Digimon with 2 or more colors attacks, you may suspend this Tamer to delete 1 of your opponent's Digimon with 3000 DP or less."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Inoue Miyako"

class BT8_085_B extends Card:
	func _init():
		name = "Yolei Inoue"
		type = Type.TAMER
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT8-085 (B)"
		play_cost = 3
		effect_text = "[Start of Your Main Phase] If you have a red Digimon in play, gain 1 memory.\n[Your Turn] When one of your Digimon with 2 or more colors attacks, you may suspend this Tamer to delete 1 of your opponent's Digimon with 3000 DP or less."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		is_parallel = true
		notes = "parallel promo Inoue Miyako"

class BT8_086 extends Card:
	func _init():
		name = "Hiro Amanokawa"
		type = Type.TAMER
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT8-086"
		play_cost = 4
		effect_text = "[Start of Your Turn] If you have 2 memory or less, set your memory to 3.\n[Your Turn] When you attack with a Digimon that has Gammamon or is level 5 or higher, you may suspend this Tamer to have 1 of your Digimon get +2000 DP for the turn."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Amanokawa Hiro"

class BT8_087 extends Card:
	func _init():
		name = "T.K. Takaishi"
		type = Type.TAMER
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "BT8-087"
		play_cost = 4
		effect_text = "[Start of Your Turn] If you have 2 memory or less, set your memory to 3.\n[Opponent Turn] When one of your opponent's Digimon attacks one of your blue Digimon, you may suspend this Tamer to [Draw 1]."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Takaishi Takeru"

class BT8_087_B extends Card:
	func _init():
		name = "T.K. Takaishi"
		type = Type.TAMER
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "BT8-087 (B)"
		play_cost = 4
		effect_text = "[Start of Your Turn] If you have 2 memory or less, set your memory to 3.\n[Opponent Turn] When one of your opponent's Digimon attacks one of your blue Digimon, you may suspend this Tamer to [Draw 1]."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		is_parallel = true
		notes = "parallel promo Takaishi Takeru"

class BT8_088 extends Card:
	func _init():
		name = "Davis Motomiya & Ken Ichijoji"
		type = Type.TAMER
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT8-088"
		play_cost = 4
		effect_text = "[Start of Your Main Phase] If you have a blue Digimon in play, gain 1 memory. If you have a green Digimon in play, gain 1 memory.\n[Your Turn] When one of your Digimon digivolves into a Digimon with 2 or more colours, you may suspend this Tamer to unsuspend that Digimon."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Motomiya Daisuke & Ichijoji Ken"

class BT8_088_B extends Card:
	func _init():
		name = "Davis Motomiya & Ken Ichijoji"
		type = Type.TAMER
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT8-088 (B)"
		play_cost = 4
		effect_text = "[Start of Your Main Phase] If you have a blue Digimon in play, gain 1 memory. If you have a green Digimon in play, gain 1 memory.\n[Your Turn] When one of your Digimon digivolves into a Digimon with 2 or more colours, you may suspend this Tamer to unsuspend that Digimon."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		is_parallel = true
		notes = "parallel promo Motomiya Daisuke & Ichijoji Ken"

class BT8_089 extends Card:
	func _init():
		name = "Cody Hida"
		type = Type.TAMER
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "BT8-089"
		play_cost = 3
		effect_text = "[Start of Your Main Phase] If you have a yellow Digimon in play, gain 1 memory.\n[Your Turn] When one of your Digimon with 2 or more colors attacks, you may suspend this Tamer to give 1 of your opponent's Digimon -2000 DP for the turn."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Hida Iori"

class BT8_089_B extends Card:
	func _init():
		name = "Cody Hida"
		type = Type.TAMER
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "BT8-089 (B)"
		play_cost = 3
		effect_text = "[Start of Your Main Phase] If you have a yellow Digimon in play, gain 1 memory.\n[Your Turn] When one of your Digimon with 2 or more colors attacks, you may suspend this Tamer to give 1 of your opponent's Digimon -2000 DP for the turn."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		is_parallel = true
		notes = "parallel promo Hida Iori"

class BT8_090 extends Card:
	func _init():
		name = "Kari Kamiya"
		type = Type.TAMER
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT8-090"
		play_cost = 4
		effect_text = "[Start of Your Turn] If you have 2 memory or less, set your memory to 3.\n[Your Turn] When a card is added to your security stack, you may suspend this Tamer to gain 1 memory."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Yagami Hikari"

class BT8_090_B extends Card:
	func _init():
		name = "Kari Kamiya"
		type = Type.TAMER
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT8-090 (B)"
		play_cost = 4
		effect_text = "[Start of Your Turn] If you have 2 memory or less, set your memory to 3.\n[Your Turn] When a card is added to your security stack, you may suspend this Tamer to gain 1 memory."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		is_parallel = true
		notes = "parallel promo Yagami Hikari"

class BT8_091 extends Card:
	func _init():
		name = "Willis"
		type = Type.TAMER
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "BT8-091"
		play_cost = 3
		effect_text = "[On Play] You may hatch 1 Digi-Egg card to an empty space in your breeding area.\n[Your Turn] When one of your Digimon digivolves into a Digimon with Gargomon, Rapidmon, text=in their name, you may suspend this Tamer to reduce the digivolution cost by 1."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Wallace"

class BT8_092 extends Card:
	func _init():
		name = "Yuji Musha"
		type = Type.TAMER
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "BT8-092"
		play_cost = 3
		effect_text = "[Your Turn] When one of your Digimon with [X-Antibody] is moved from your breeding area to your battle area, gain 1 memory and [Draw 1].\n[Your Turn] When one of your black Digimon with [X-Antibody] attacks, you may suspend this Tamer to place 1 card with [X-Antibody] from your hand under that Digimon as its bottom digivolution card."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Musha Yuuji"

class BT8_093 extends Card:
	func _init():
		name = "Yukio Oikawa"
		type = Type.TAMER
		color = ColorGroup.PURPLE
		rarity = Rarity.R
		id = "BT8-093"
		play_cost = 3
		effect_text = "[All Turns] When one of your Digimon with Myotismon is deleted, you may suspend this Tamer to gain 1 memory.\n [End of Opponent's Turn] If this Tamer is suspended, you may delete this Tamer to play 1 [MaloMyotismon]  from your trash without paying its memory cost."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Oikawa Yukio"

class BT8_094 extends Card:
	func _init():
		name = "Digimon Emperor"
		type = Type.TAMER
		color = ColorGroup.WHITE
		rarity = Rarity.R
		id = "BT8-094"
		play_cost = 3
		effect_text = "[All Turns] When one of your opponent's level 5 or lower Digimon is deleted, you may suspend this Tamer to [Draw 1]\n[Opponent Turn] When one of your opponent's level 3 Digimon is moved from their breeding area to their battle area, gain 2 memory."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Digimon Kaiser"

class BT8_095 extends Card:
	func _init():
		name = "Fire Rocket"
		type = Type.OPTION
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT8-095"
		play_cost = 1
		effect_text = "While you have a Digimon with [Armor Form] in play, you may use this card without meeting its color requirements.\n[Main] 1 of your Digimon with 2 or more colors gains [Security Attack +1] for the turn."
		sec_effect_text = "[Security] Delete 1 of your opponent's Digimon with [Blocker]."

class BT8_096 extends Card:
	func _init():
		name = "Top Gun"
		type = Type.OPTION
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT8-096"
		play_cost = 3
		effect_text = "[Main] Delete 1 of your opponent's Digimon with 4000 DP or less. If you have a Digimon in play with 2 or more colors, or with 2 or more colors in its digivolution cards, delete 1 of your opponent's Digimon with 7000 DP or less instead."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class BT8_097 extends Card:
	func _init():
		name = "Crimson Blaze"
		type = Type.OPTION
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT8-097"
		play_cost = 6
		effect_text = "Reduce the memory cost of this card in your hand by 1 for each Digimon your opponent has in play.\n[Main] Delete all of your opponent's Digimon with 6000 DP or less. Your opponent can't play Digimon by effects until the end of their next turn."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class BT8_098 extends Card:
	func _init():
		name = "Innocence Blizzard"
		type = Type.OPTION
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "BT8-098"
		play_cost = 3
		effect_text = "[Main] Trash the bottom digivolution card of all of your opponent's Digimon. Then, up to 3 of your opponent's Digimon with no digivolution cards can't attack or block until the end of your opponent's next turn."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class BT8_099 extends Card:
	func _init():
		name = "Giga Death"
		type = Type.OPTION
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT8-099"
		play_cost = 9
		effect_text = "[Main] Suspend 1 of your opponent's Digimon. Then, place up to 10 of your opponent's suspended Digimon at the bottom of their owners' decks in any order."
		sec_effect_text = "[Security] Suspend 1 of your opponent's Digimon. Then, return 1 of your opponent's suspended Digimon to the bottom of its owner's deck."

class BT8_100 extends Card:
	func _init():
		name = "Disaster Blaster"
		type = Type.OPTION
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT8-100"
		play_cost = 3
		effect_text = "[Main] 1 of your opponent's Digimon gets -3000 DP for the turn. If you have a Digimon in play with 2 or more colors, or with 2 or more colors in its digivolution cards, 1 of your opponent's Digimon gets -6000 DP instead."
		sec_effect_text = "[Security] Activate this card's [Main] effect."
		notes = "Aramitama"

class BT8_101 extends Card:
	func _init():
		name = "Plasma Shot"
		type = Type.OPTION
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT8-101"
		play_cost = 4
		effect_text = "While you have a Digimon with [Armor Form] in play, you may use this card without meeting its color requirements.\n[Main] 1 of your opponent's Digimon gets -4000 DP for the turn, and all of your opponent's Digimon get -1000 DP for the turn for each card with [Armor Form] in your trash."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class BT8_102 extends Card:
	func _init():
		name = "Samādhi Śānti"
		type = Type.OPTION
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "BT8-102"
		play_cost = 1
		effect_text = "[Main] You may suspend 1 of your opponent's Digimon or Tamers by suspending 1 of your Digimon. Your opponent's cards suspended with this effect can't unsuspend until the end of their next turn."
		sec_effect_text = "[Security] Suspend 1 of your opponent's Digimon or Tamers."

class BT8_103 extends Card:
	func _init():
		name = "Lightning Blade"
		type = Type.OPTION
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT8-103"
		play_cost = 1
		effect_text = "While you have a Digimon with [Armor Form] in play, you may use this card without meeting its color requirements.\n[Main] 1 of your Digimon with 2 or more colors gets +2000 DP and [Piercing] for the turn."
		sec_effect_text = "[Security] Suspend 1 of your opponent's Digimon."

class BT8_104 extends Card:
	func _init():
		name = "Eiseiryūoujin"
		type = Type.OPTION
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "BT8-104"
		play_cost = 4
		effect_text = "[Main] [De-Digivolve 1]. Then, you may place 1 card with [X-Antibody] from your hand as the bottom digivolution card of 1 of your black Digimon with [X-Antibody] to delete 1 of your opponent's Digimon with a play cost of 4 or less."
		sec_effect_text = "[Security] [De-Digivolve 1]. Then, delete 1 of your opponent's Digimon with a play cost of 4 or less."

class BT8_105 extends Card:
	func _init():
		name = "Dark Gaia Force"
		type = Type.OPTION
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "BT8-105"
		play_cost = 8
		effect_text = "[Main]  Choose any number of your opponent's Digimon whose play costs add up to 15 or less and delete them."
		sec_effect_text = "[Security] Delete 1 of your opponent's Digimon with a play cost of 15 or less."

class BT8_106 extends Card:
	func _init():
		name = "Senbon Dokkān"
		type = Type.OPTION
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT8-106"
		play_cost = 9
		effect_text = "[Main] Reveal the top 3 cards of your deck. You may play any number of Digimon cards with Mamemon, text=in their name whose play costs add up to 15 or less among them without paying their memory costs. Delete 1 of your opponent's Digimon with a play cost of 6 or less for each Digimon played with this effect. Trash the remaining cards."
		sec_effect_text = "[Security] Activate this card's [Main] effect."
		notes = "Thousand Blasting"

class BT8_107 extends Card:
	func _init():
		name = "Pandemonium Flame"
		type = Type.OPTION
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT8-107"
		play_cost = 2
		effect_text = "[Main] You may delete 1 of your Digimon to delete 1 of your opponent's unsuspended Digimon with a level less than or equal to the deleted Digimon's level."
		sec_effect_text = "[Security] Delete 1 of your opponent's unsuspended Digimon."

class BT8_108 extends Card:
	func _init():
		name = "Mist Memory Boost!"
		type = Type.OPTION
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT8-108"
		play_cost = 3
		effect_text = "[Main] Trash the top 2 cards of your deck and [Draw 1]. Then, place this card in your Battle Area.\n[Main] [Delay]\n·Gain 2 memory."
		sec_effect_text = "[Security] Place this card in its owner's battle area."

class BT8_109 extends Card:
	func _init():
		name = "Flame Hellscythe"
		type = Type.OPTION
		color = ColorGroup.PURPLE
		rarity = Rarity.R
		id = "BT8-109"
		play_cost = 6
		effect_text = "[Main] 1 of your opponent's Digimon gets -6000 DP for the turn. Then, play 1 purple or yellow Digimon card with 6000 DP or less from your trash without paying its memory cost."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class BT8_110 extends Card:
	func _init():
		name = "Armor Texture!"
		type = Type.OPTION
		color = ColorGroup.WHITE
		rarity = Rarity.C
		id = "BT8-110"
		play_cost = 0
		effect_text = "While you have a Digimon with [Armor Form] in play, you may use this card without meeting its color requirements.\n[Main]  Trash the top card of 1 of your Digimon with [Armor Form]. Then, you may digivolve 1 of your Digimon into a Digimon card in your hand with [Armor Form] for its digivolution cost. If you do, unsuspend that Digimon."
		sec_effect_text = "[Security] Play 1 level 3 Digimon card with [Free] from your hand or trash without paying its memory cost."

class BT8_111 extends Card:
	func _init():
		name = "Creepymon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.SEC
		id = "BT8-111"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Demon Lord"
		power = 11000
		effect_text = "[When Digivolved] Trash the top 2 cards of your deck for each of your opponent's Digimon in play. If you trash 4 or more cards with this effect, you may play 1 level 5 or lower purple Digimon card from your trash without paying its memory cost.\n[When Attacking] [Once Per Turn] For every 10 cards in your trash, trash the top 3 cards of your opponent's deck, and this Digimon gets +3000 DP for the turn."
		notes = "Demon"

class BT8_111_B extends Card:
	func _init():
		name = "Creepymon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.SEC
		id = "BT8-111 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Demon Lord"
		power = 11000
		effect_text = "[When Digivolved] Trash the top 2 cards of your deck for each of your opponent's Digimon in play. If you trash 4 or more cards with this effect, you may play 1 level 5 or lower purple Digimon card from your trash without paying its memory cost.\n[When Attacking] [Once Per Turn] For every 10 cards in your trash, trash the top 3 cards of your opponent's deck, and this Digimon gets +3000 DP for the turn."
		is_parallel = true
		notes = "parallel promo Demon"

class BT8_112 extends Card:
	func _init():
		name = "Imperialdramon Paladin Mode"
		type = Type.DIGIMON
		color = ColorGroup.WHITE
		rarity = Rarity.SEC
		id = "BT8-112"
		play_cost = 15
		level = 7
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 7
		digivolve_level = 6
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 7
		digivolve_level_2 = 6
		digimon_type = "Ancient Holy Warrior"
		power = 16000
		effect_text = "When one of your Digimon would digivolve into this card in your hand, you may return 1 white level 7 Digimon card from your trash to the bottom of your deck to reduce the digivolution cost by 4.\n[When Digivolved] [When Attacking] You may return 1 2-color card from this Digimon's digivolution cards to the bottom of its owner's deck to trash all of the digivolution cards of 1 of your opponent's Digimon. Then, return all of your opponent's Digimon with no digivolution cards to the bottom of their owners' decks in any order."

class BT8_112_B extends Card:
	func _init():
		name = "Imperialdramon Paladin Mode"
		type = Type.DIGIMON
		color = ColorGroup.WHITE
		rarity = Rarity.SEC
		id = "BT8-112 (B)"
		play_cost = 15
		level = 7
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 7
		digivolve_level = 6
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 7
		digivolve_level_2 = 6
		digimon_type = "Ancient Holy Warrior"
		power = 16000
		effect_text = "When one of your Digimon would digivolve into this card in your hand, you may return 1 white level 7 Digimon card from your trash to the bottom of your deck to reduce the digivolution cost by 4.\n[When Digivolved] [When Attacking] You may return 1 2-color card from this Digimon's digivolution cards to the bottom of its owner's deck to trash all of the digivolution cards of 1 of your opponent's Digimon. Then, return all of your opponent's Digimon with no digivolution cards to the bottom of their owners' decks in any order."
		is_parallel = true
		notes = "parallel promo"

