# Content autogenerated. Data from digimoncardgame.fandom.com

static func register_cards():

	CardDB.register_booster("BT-10", "BT-10: Xros Encounter")
	CardDB.add_card(BT10_001.new())
	CardDB.add_card(BT10_002.new())
	CardDB.add_card(BT10_003.new())
	CardDB.add_card(BT10_004.new())
	CardDB.add_card(BT10_005.new())
	CardDB.add_card(BT10_006.new())
	CardDB.add_card(BT10_007.new())
	CardDB.add_card(BT10_008.new())
	CardDB.add_card(BT10_009.new())
	CardDB.add_card(BT10_010.new())
	CardDB.add_card(BT10_011.new())
	CardDB.add_card(BT10_012.new())
	CardDB.add_card(BT10_013.new())
	CardDB.add_card(BT10_014.new())
	CardDB.add_card(BT10_015.new())
	CardDB.add_card(BT10_016.new())
	CardDB.add_card(BT10_017.new())
	CardDB.add_card(BT10_018.new())
	CardDB.add_card(BT10_019.new())
	CardDB.add_card(BT10_020.new())
	CardDB.add_card(BT10_021.new())
	CardDB.add_card(BT10_022.new())
	CardDB.add_card(BT10_023.new())
	CardDB.add_card(BT10_024.new())
	CardDB.add_card(BT10_025.new())
	CardDB.add_card(BT10_026.new())
	CardDB.add_card(BT10_027.new())
	CardDB.add_card(BT10_028.new())
	CardDB.add_card(BT10_029.new())
	CardDB.add_card(BT10_030.new())
	CardDB.add_card(BT10_031.new())
	CardDB.add_card(BT10_032.new())
	CardDB.add_card(BT10_033.new())
	CardDB.add_card(BT10_034.new())
	CardDB.add_card(BT10_035.new())
	CardDB.add_card(BT10_036.new())
	CardDB.add_card(BT10_037.new())
	CardDB.add_card(BT10_038.new())
	CardDB.add_card(BT10_039.new())
	CardDB.add_card(BT10_040.new())
	CardDB.add_card(BT10_041.new())
	CardDB.add_card(BT10_042.new())
	CardDB.add_card(BT10_043.new())
	CardDB.add_card(BT10_044.new())
	CardDB.add_card(BT10_045.new())
	CardDB.add_card(BT10_046.new())
	CardDB.add_card(BT10_047.new())
	CardDB.add_card(BT10_048.new())
	CardDB.add_card(BT10_049.new())
	CardDB.add_card(BT10_050.new())
	CardDB.add_card(BT10_051.new())
	CardDB.add_card(BT10_052.new())
	CardDB.add_card(BT10_053.new())
	CardDB.add_card(BT10_054.new())
	CardDB.add_card(BT10_055.new())
	CardDB.add_card(BT10_056.new())
	CardDB.add_card(BT10_057.new())
	CardDB.add_card(BT10_058.new())
	CardDB.add_card(BT10_059.new())
	CardDB.add_card(BT10_060.new())
	CardDB.add_card(BT10_061.new())
	CardDB.add_card(BT10_062.new())
	CardDB.add_card(BT10_063.new())
	CardDB.add_card(BT10_064.new())
	CardDB.add_card(BT10_065.new())
	CardDB.add_card(BT10_066.new())
	CardDB.add_card(BT10_067.new())
	CardDB.add_card(BT10_068.new())
	CardDB.add_card(BT10_069.new())
	CardDB.add_card(BT10_070.new())
	CardDB.add_card(BT10_071.new())
	CardDB.add_card(BT10_072.new())
	CardDB.add_card(BT10_073.new())
	CardDB.add_card(BT10_074.new())
	CardDB.add_card(BT10_075.new())
	CardDB.add_card(BT10_076.new())
	CardDB.add_card(BT10_077.new())
	CardDB.add_card(BT10_078.new())
	CardDB.add_card(BT10_079.new())
	CardDB.add_card(BT10_080.new())
	CardDB.add_card(BT10_081.new())
	CardDB.add_card(BT10_082.new())
	CardDB.add_card(BT10_083.new())
	CardDB.add_card(BT10_084.new())
	CardDB.add_card(BT10_085.new())
	CardDB.add_card(BT10_086.new())
	CardDB.add_card(BT10_087.new())
	CardDB.add_card(BT10_088.new())
	CardDB.add_card(BT10_089.new())
	CardDB.add_card(BT10_090.new())
	CardDB.add_card(BT10_091.new())
	CardDB.add_card(BT10_092.new())
	CardDB.add_card(BT10_093.new())
	CardDB.add_card(BT10_094.new())
	CardDB.add_card(BT10_095.new())
	CardDB.add_card(BT10_096.new())
	CardDB.add_card(BT10_097.new())
	CardDB.add_card(BT10_098.new())
	CardDB.add_card(BT10_099.new())
	CardDB.add_card(BT10_100.new())
	CardDB.add_card(BT10_101.new())
	CardDB.add_card(BT10_102.new())
	CardDB.add_card(BT10_103.new())
	CardDB.add_card(BT10_104.new())
	CardDB.add_card(BT10_105.new())
	CardDB.add_card(BT10_106.new())
	CardDB.add_card(BT10_107.new())
	CardDB.add_card(BT10_108.new())
	CardDB.add_card(BT10_109.new())
	CardDB.add_card(BT10_110.new())
	CardDB.add_card(BT10_111.new())
	CardDB.add_card(BT10_112.new())

class BT10_001 extends Card:
	func _init():
		name = "DemiMeramon"
		type = Type.DIGITAMA
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT10-001"
		level = 2
		stage_level = Stage.HYBRID
		digimon_type = "Flame"
		inherited_effect_text = "[Your Turn] While this Digimon has a non-red card in its digivolution cards, it gets +1000 DP."

class BT10_002 extends Card:
	func _init():
		name = "Bebydomon"
		type = Type.DIGITAMA
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "BT10-002"
		level = 2
		stage_level = Stage.HYBRID
		digimon_type = "Baby Dragon"
		inherited_effect_text = "[When Attacking] (Once Per Turn) If your opponent has 2 or more Digimon in play, <Draw 1> (Draw 1 card from your deck)."

class BT10_003 extends Card:
	func _init():
		name = "Pickmons"
		type = Type.DIGITAMA
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT10-003"
		level = 2
		stage_level = Stage.HYBRID
		digimon_type = "Minor/Xros Heart"
		inherited_effect_text = "[When Attacking] If this Digimon has [Xros Heart] in its traits, <Draw 1> (Draw 1 card from your deck)."

class BT10_004 extends Card:
	func _init():
		name = "Bosamon"
		type = Type.DIGITAMA
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "BT10-004"
		level = 2
		stage_level = Stage.HYBRID
		digimon_type = "Lesser"
		inherited_effect_text = "[Your Turn] (Once Per Turn) When a Digimon is suspended by an effect, this Digimon gets +1000 DP for the turn."

class BT10_005 extends Card:
	func _init():
		name = "Monimon"
		type = Type.DIGITAMA
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "BT10-005"
		level = 2
		stage_level = Stage.HYBRID
		digimon_type = "CRT/Twilight/Xros Heart"
		inherited_effect_text = "[All Turns] While this Digimon has [Twilight] in its traits, it gets +1000 DP."

class BT10_006 extends Card:
	func _init():
		name = "Tokomon"
		type = Type.DIGITAMA
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT10-006"
		level = 2
		stage_level = Stage.HYBRID
		digimon_type = "Lesser"
		inherited_effect_text = "[Opponent's Turn] When this card is trashed from digivolution cards by an effect, <Draw 1> (Draw 1 card from your deck)."

class BT10_007 extends Card:
	func _init():
		name = "Dondokomon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT10-007"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Musical Instrument/Xros Heart"
		power = 4000

class BT10_008 extends Card:
	func _init():
		name = "Shoutmon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT10-008"
		play_cost = 4
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Mini Dragon/Xros Heart"
		power = 2000
		effect_text = "[On Play]  Reveal the top 3 cards of your deck. Add 1 Digimon card and 1 Tamer card―both with [Xros Heart] in their traits―among them to your hand. Place the rest at the bottom of your deck in any order.\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[Your Turn] While this Digimon has [Shoutmon] in its name, it gains <Rush> (This Digimon can attack the turn it comes into play)."

class BT10_009 extends Card:
	func _init():
		name = "Shoutmon X4"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT10-009"
		play_cost = 9
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color_2 = ""
		digivolve_cost_2 = 3
		digivolve_level_2 = 3
		digimon_type = "Composite/Xros Heart"
		power = 8000
		effect_text = "<Material Save 2> (When this Digimon would be deleted, you may place 2 cards in this Digimon's DigiXros requirements from this Digimon's digivolution cards under 1 of your Tamers.\n[On Play] <Draw 2> (Draw 2 cards from your deck).\n[End of Attack] By placing all digivolution cards from under this Digimon under 1 of your Tamers, unsuspend 1 of your Tamers, and delete this Digimon."

class BT10_010 extends Card:
	func _init():
		name = "Asuramon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT10-010"
		play_cost = 7
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Wizard"
		power = 8000

class BT10_011 extends Card:
	func _init():
		name = "Canoweissmon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT10-011"
		play_cost = 8
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Sky Dragon"
		power = 8000
		effect_text = "[Your Turn] (Once Per Turn) When one of your Tamers becomes suspended, this Digimon gets +2000 DP for the turn. Then, if this Digimon has 12000 DP or more, it gains <Security Attack +1> (This Digimon checks 1 additional security card) for the turn.\n[All Turns] This Digimon gains all effects of cards with [Gammamon] in their names in this Digimon's digivolution cards."
		inherited_effect_text = "[All Turns] This Digimon gains all effects of cards with [Gammamon] in their names in this Digimon's digivolution cards."

class BT10_012 extends Card:
	func _init():
		name = "Shoutmon X4B"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT10-012"
		play_cost = 9
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color_2 = ""
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Composite/Xros Heart"
		power = 9000
		effect_text = "<Armor Purge>  (When this Digimon would be deleted, you may trash the top card of this Digimon to prevent that deletion).\n[On Play] [When Digivolving] You may place 1 Digimon card with [Xros Heart] in its traits from your hand or from under one of your Tamers under this Digimon as its bottom digivolution card. Then, if [Beelzemon] is in this Digimon's digivolution cards, return 2 cards with [Xros Heart] in their traits from your trash to your hand."

class BT10_013 extends Card:
	func _init():
		name = "Shoutmon X5"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.SR
		id = "BT10-013"
		play_cost = 10
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color_2 = ""
		digivolve_cost_2 = 4
		digivolve_level_2 = 4
		digimon_type = "Composite/Xros Heart"
		power = 10000
		effect_text = "<Security Attack +1> (This Digimon checks 1 additional security card).\n<Blocker> (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead).\n<Material Save 3> (When this Digimon would be deleted, you may place 3 cards in this Digimon's DigiXros requirements from this Digimon's digivolution cards under 1 of your Tamers."

class BT10_014 extends Card:
	func _init():
		name = "PileVolcamon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT10-014"
		play_cost = 10
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Cyborg"
		power = 11000
		effect_text = "[When Digivolving] <Blitz> (If your opponent has 1 or more memory, this Digimon may attack).\n[Your Turn] This Digimon gets +2000 DP."

class BT10_015 extends Card:
	func _init():
		name = "Shoutmon X5B"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT10-015"
		play_cost = 11
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color_2 = ""
		digivolve_cost_2 = 4
		digivolve_level_2 = 5
		digimon_type = "Composite/Xros Heart"
		power = 11000
		effect_text = "<Blocker> (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead).\n<Armor Purge>  (When this Digimon would be deleted, you may trash the top card of this Digimon to prevent that deletion).\n[On Play] [When Digivolving] You may place 1 Digimon card with [Xros Heart] in its traits from your hand or from under one of your Tamers under this Digimon as its bottom digivolution card. Then, if [Beelzemon] is in this Digimon's digivolution cards, you may play 1 level 4 or lower Digimon card with [Xros Heart] in its traits from your trash without paying its memory cost."

class BT10_016 extends Card:
	func _init():
		name = "Jesmon (X Antibody)"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.SR
		id = "BT10-016"
		play_cost = 12
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Holy Warrior/Royal Knight/X Antibody"
		power = 11000
		effect_text = "<Piercing> (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would).\n[When Digivolving] You may play 1 Digimon card with [Sistermon] in its name from your hand or trash without paying its memory cost. Then, if [Jesmon] is in this Digimon's digivolution cards or you have a Digimon with [Sistermon] in its name in play, until the end of your opponent's turn, all of your Digimon can also attack your opponent's unsuspended Digimon and get +2000 DP."

class BT10_017 extends Card:
	func _init():
		name = "Bulucomon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT10-017"
		play_cost = 2
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Mini Dragon"
		power = 5000

class BT10_018 extends Card:
	func _init():
		name = "Gaossmon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT10-018"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Reptile/Blue Flare"
		power = 1000
		effect_text = "[On Deletion] You may play 1 level 4 Digimon card with [Blue Flare] in its traits from your hand suspended without paying its memory cost."

class BT10_019 extends Card:
	func _init():
		name = "Greymon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT10-019"
		play_cost = 4
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Dinosaur/Blue Flare"
		power = 4000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 2 cards with [Blue Flare] in their traits among them to your hand. Place the rest at the bottom of your deck in any order. If you have a [Christopher Aonuma] in play, you may return 1 [MetalGreymon] from your trash to your hand instead.\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[When Attacking] (Once Per Turn) If this Digimon has [Blue Flare] in its traits and your opponent has 2 or more Digimon in play, unsuspend this Digimon."

class BT10_020 extends Card:
	func _init():
		name = "Deckerdramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "BT10-020"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Cyborg/Blue Flare"
		power = 5000
		effect_text = "[On Play] <Draw 1> (Draw 1 card from your deck). Then, for each Digimon your opponent has in play, <Draw 1> (Draw 1 card from your deck).\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[All Turns] While your opponent has 2 or more Digimon in play, this Digimon gets +1000 DP."

class BT10_021 extends Card:
	func _init():
		name = "MailBirdramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "BT10-021"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Machine/Blue Flare"
		power = 5000
		effect_text = "[On Play] If you have a [Christopher Aonuma] in play, you may return 1 [MetalGreymon] from your trash to your hand. If you don't have a [Christopher Aonuma] in play, you may play one from your hand without paying its memory cost.\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[When Attacking] (Once Per Turn) If this Digimon has [Blue Flare] in its traits and your opponent has 2 or more Digimon in play, 1 of your opponent's Digimon can't attack or block until your opponent's next end of turn."

class BT10_022 extends Card:
	func _init():
		name = "Brachiomon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT10-022"
		play_cost = 6
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color_2 = ""
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Plesiosaur"
		power = 9000

class BT10_023 extends Card:
	func _init():
		name = "Thetismon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT10-023"
		play_cost = 7
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Aquabeast"
		power = 7000
		effect_text = "[When Digivolving] If you have 6 or fewer cards in your hand, <Draw 2> (Draw 2 cards from your deck).\n[When Attacking] (Once Per Turn) If you have 8 or more cards in your hand, by trashing 2 cards in your hand, unsuspend this Digimon."

class BT10_024 extends Card:
	func _init():
		name = "MetalGreymon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.SR
		id = "BT10-024"
		play_cost = 7
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Cyborg/Blue Flare"
		power = 8000
		effect_text = "<Material Save 2> (When this Digimon would be deleted, you may place 2 cards in this Digimon's DigiXros requirements from this Digimon's digivolution cards under 1 of your Tamers\n[On Play] This Digimon gains <Rush> (This Digimon can attack the turn it comes into play) for the turn. Then, if DigiXrosing, 3 of your opponent's Digimon with digivolution cards less than or equal to this Digimon's digivolution cards can't attack or block until the end of your opponent's turn."

class BT10_025 extends Card:
	func _init():
		name = "Cyberdramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT10-025"
		play_cost = 8
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Alien Humanoid/Blue Flare"
		power = 7000
		effect_text = "(Hand) [Main] If you have a Digimon with [Blue Flare] in its traits in play, by paying 3 memory, place this card under that Digimon as its bottom digivolution card. Then, unsuspend that Digimon."
		inherited_effect_text = "[All Turns] While your opponent has 2 or more Digimon in play, this Digimon gets +1000 DP."

class BT10_026 extends Card:
	func _init():
		name = "DeckerGreymon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT10-026"
		play_cost = 9
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digivolve_color_2 = ""
		digivolve_cost_2 = 2
		digivolve_level_2 = 5
		digimon_type = "Cyborg/Blue Flare"
		power = 10000
		effect_text = "<Armor Purge>  (When this Digimon would be deleted, you may trash the top card of this Digimon to prevent that deletion)\n[On Play] [When Digivolving] You may place 1 Digimon card with [Blue Flare] in its traits from your hand or from under one of your Tamers under this Digimon as its bottom digivolution card. Then, if [Deckerdramon] is in this Digimon's digivolution cards, 1 of your opponent's Digimon can't attack or block until the end of your opponent's turn."

class BT10_027 extends Card:
	func _init():
		name = "Regalecusmon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT10-027"
		play_cost = 11
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Aquatic"
		power = 11000
		effect_text = "[When Digivolving] Trash 2 digivolution cards from the bottom of 1 of your opponent's Digimon.\n[When Attacking] If your opponent has a Digimon with no digivolution cards in play, you may play 1 level 3 Digimon card and 1 level 4 Digimon card from this Digimon's digivolution cards without paying their memory costs."

class BT10_028 extends Card:
	func _init():
		name = "Cannondramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT10-028"
		play_cost = 13
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color_2 = ""
		digivolve_cost_2 = 4
		digivolve_level_2 = 5
		digimon_type = "Cyborg"
		power = 12000
		effect_text = "<Blocker> (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead).\n[When Digivolving] Unsuspend this Digimon.\n[Opponent's Turn] (Once Per Turn) When this Digimon deletes an opponent's Digimon in battle, unsuspend this Digimon."

class BT10_029 extends Card:
	func _init():
		name = "Starmons"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT10-029"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Major/Xros Heart"
		power = 1000
		effect_text = "[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[When Attacking] If this Digimon has [Shoutmon] in its name, <Draw 1> (Draw 1 card from your deck)."

class BT10_030 extends Card:
	func _init():
		name = "Tinkermon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT10-030"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Fairy"
		power = 2000
		effect_text = "[On Play] 1 of your opponent's level 5 or lower Digimon gains <Security Attack -1> (This Digimon checks 1 fewer security card) until the end of your opponent's turn."

class BT10_031 extends Card:
	func _init():
		name = "Pulsemon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT10-031"
		play_cost = 3
		level = 0
		stage_level = ""
		attribute = Attribute.VACCINE
		digimon_type = "Beastkin"
		power = 2000
		effect_text = "[Opponent's Turn] While you have 3 or fewer security cards, this Digimon gains <Blocker> (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead)."

class BT10_032 extends Card:
	func _init():
		name = "Renamon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT10-032"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Beastkin"
		power = 1000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 Option card with [Plug-In] in its name and 1 yellow Tamer among them to your hand. Place the rest at the bottom of your deck in any order."
		inherited_effect_text = "[Your Turn] (Once Per Turn) When you use an Option card with a memory cost of 2 or more, 1 of your opponent's Digimon gets -2000 DP for the turn."

class BT10_033 extends Card:
	func _init():
		name = "Shortmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT10-033"
		play_cost = 3
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Food"
		power = 3000

class BT10_034 extends Card:
	func _init():
		name = "Dorulumon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT10-034"
		play_cost = 4
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Beast/Xros Heart"
		power = 4000
		effect_text = "[On Play] If you have another Digimon or Tamer with [Xros Heart] in its traits, 1 of your opponent's Digimon gets -3000 DP until of the end your opponent's next turn.\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[Your Turn] While this Digimon has [Shoutmon] in its name, all of your opponent's Security Digimon get -2000 DP."

class BT10_035 extends Card:
	func _init():
		name = "Darcmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT10-035"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Angel"
		power = 4000
		inherited_effect_text = "[When Attacking] (Once Per Turn) 1 of your opponent's Digimon gains <Security Attack -1> (This Digimon checks 1 fewer security card) until the end of your opponent's turn."

class BT10_036 extends Card:
	func _init():
		name = "Kyubimon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT10-036"
		play_cost = 6
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Mysterious Beast"
		power = 5000
		effect_text = "[When Digivolving] You may activate 1 of the effects below.\n・Return 1 Option card with [Plug-In] in its name from your trash to your hand.\n・By trashing 1 Option card with [Plug-In] in its name in your hand, <Draw 2> (Draw 2 cards from your deck)."

class BT10_037 extends Card:
	func _init():
		name = "Weddinmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT10-037"
		play_cost = 7
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Fairy"
		power = 8000

class BT10_038 extends Card:
	func _init():
		name = "Sanzomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "BT10-038"
		play_cost = 7
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Monk"
		power = 7000
		effect_text = "[When Digivolving] 1 of your opponent's Digimon gains <Security Attack -1> (This Digimon checks 1 fewer security card) until the end of your opponent's turn."
		inherited_effect_text = "[When Attacking] (Once Per Turn) 1 of your opponent's Digimon gains <Security Attack -1> (This Digimon checks 1 fewer security card) until the end of your opponent's turn."

class BT10_039 extends Card:
	func _init():
		name = "Taomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT10-039"
		play_cost = 8
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Wizard"
		power = 8000
		effect_text = "[When Digivolving] You may use 1 Option card with [Plug-In] in its name from your hand without meeting its color requirements or paying its memory cost."

class BT10_040 extends Card:
	func _init():
		name = "Achillesmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "BT10-040"
		play_cost = 12
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digivolve_color_2 = ""
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Beastkin"
		power = 11000
		effect_text = "[When Digivolving] If you have 2 or fewer security cards, <Recovery +1 (Deck)> (Place the top card of your deck on top of your security stack).\n[When Attacking] (Once Per Turn) If you have 3 or more security cards, 1 of your opponent's Digimon gets -5000 DP for the turn. If you have 3 or fewer security cards, gain 2 memory."

class BT10_041 extends Card:
	func _init():
		name = "Sakuyamon: Maid Mode"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "BT10-041"
		play_cost = 12
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color_2 = ""
		digivolve_cost_2 = 2
		digivolve_level_2 = 6
		digimon_type = "Shaman"
		power = 11000
		effect_text = "[When Digivolving] You may use 1 Option card with [Plug-In] in its name or that's yellow and has a memory cost of 5 or less from your hand without meeting its color requirements or paying its memory cost. Place the Option card used with this effect on top of your security stack face down instead of placing it in your trash.\n[When Attacking] You may digivolve this Digimon into a [Sakuyamon] in your hand for 1 memory, ignoring its digivolution requirements."
		notes = "Sakuyamon: Miko Mode"

class BT10_042 extends Card:
	func _init():
		name = "Venusmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "BT10-042"
		play_cost = 13
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Shaman/Olympos XII"
		power = 12000
		effect_text = "[When Digivolving] All of your opponent's Digimon gain <Security Attack -1> (This Digimon checks 1 fewer security card) until the end of your opponent's turn.\n[Opponent's Turn] Your opponent's Digimon with <Security Attack> can't attack this Digimon and can't activate [When Attacking] and [When Digivolving] effects."

class BT10_043 extends Card:
	func _init():
		name = "Mushroomon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT10-043"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Vegetation"
		power = 3000

class BT10_044 extends Card:
	func _init():
		name = "Angoramon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "BT10-044"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Beast"
		power = 2000
		effect_text = "[Your Turn] (Once Per Turn) When you play a green Tamer, <Draw 1> (Draw 1 card from your deck)."
		inherited_effect_text = "[Your Turn] (Once Per Turn) When an opponent's Digimon becomes suspended, <Draw 1> (Draw 1 card from your deck)."

class BT10_045 extends Card:
	func _init():
		name = "Kokuwamon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT10-045"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Data"
		power = 2000
		inherited_effect_text = "[Your Turn] (Once Per Turn) When this Digimon deletes an opponent's Digimon in battle, gain 1 memory."

class BT10_046 extends Card:
	func _init():
		name = "Palmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "BT10-046"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Vegetation"
		power = 2000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 card with [Vegetation], or [Plant] in one of its traits, and 1 card with [Fairy] in its traits among them to your hand. Place the rest at the bottom of your deck in any order."

class BT10_047 extends Card:
	func _init():
		name = "RedVegiemon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT10-047"
		play_cost = 3
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Vegetation"
		power = 3000

class BT10_048 extends Card:
	func _init():
		name = "Sunflowmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT10-048"
		play_cost = 4
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Vegetation"
		power = 3000
		effect_text = "[When Digivolving] By suspending 1 of your green Digimon, you may play 1 Digimon card with [Vegetation], [Plant], or [Fairy] in one of its traits and 3000 DP or less from your hand without paying its play cost."
		inherited_effect_text = "[Your Turn] (Once Per Turn) When an effect suspends one of your Digimon, <Draw 1> (Draw 1 card from your deck)."

class BT10_049 extends Card:
	func _init():
		name = "Ballistamon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT10-049"
		play_cost = 4
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Machine/Xros Heart"
		power = 4000
		effect_text = "[Opponent's Turn] While you have another Digimon or Tamer with [Xros Heart] in its traits in play, this Digimon gains <Blocker> (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead).\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[Your Turn] While this Digimon has [Shoutmon] in its name, it gains <Piercing> (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would)."

class BT10_050 extends Card:
	func _init():
		name = "WezenGammamon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT10-050"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Ceratopsian"
		power = 6000
		effect_text = "<Piercing> (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would)."

class BT10_051 extends Card:
	func _init():
		name = "SymbareAngoramon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT10-051"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Beastkin"
		power = 6000
		inherited_effect_text = "[Your Turn] (Once Per Turn) When an opponent's Digimon becomes suspended, gain 1 memory."

class BT10_052 extends Card:
	func _init():
		name = "Cherrymon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT10-052"
		play_cost = 7
		level = 5
		stage_level = Stage.HYBRID
		attribute = ""
		digimon_type = "Vegetation"
		power = 7000
		effect_text = "<Digisorption -2> (When one of your Digimon digivolves into this card from your hand, you may suspend 1 of your Digimon to reduce the memory cost of the digivolution by 2).\n[Your Turn] (Once Per Turn)  When an opponent's Digimon attacks, you may switch the target of attack to 1 of your suspended Digimon."

class BT10_053 extends Card:
	func _init():
		name = "Ajatarmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "BT10-053"
		play_cost = 8
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Vegetation"
		power = 7000
		effect_text = "[Main] (Once Per Turn) By suspending 1 of your green Digimon, you may play 1 Digimon card with [Vegetation], [Plant], or [Fairy] in one of its traits and 3000 DP or less from your hand without paying its memory cost."
		inherited_effect_text = "[Your Turn] (Once Per Turn) When an effect suspends one of your Digimon, gain 1 memory."

class BT10_054 extends Card:
	func _init():
		name = "Lamortmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "BT10-054"
		play_cost = 8
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Beast"
		power = 9000
		effect_text = "[When Digivolving] Suspend 1 of your opponent's Digimon.\n[Your Turn] (Once Per Turn) When this Digimon deletes an opponent's Digimon in battle, unsuspend it.\n[When Attacking] If you don't have a Tamer in play, lose 2 memory."

class BT10_055 extends Card:
	func _init():
		name = "Gryphonmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "BT10-055"
		play_cost = 10
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color_2 = ""
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Mythical Beast"
		power = 13000

class BT10_056 extends Card:
	func _init():
		name = "Lotosmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "BT10-056"
		play_cost = 11
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Fairy"
		power = 11000
		effect_text = "[When Digivolving] Suspend 1 of your opponent's Digimon. It doesn't unsuspend during your opponent's next unsuspend phase.\n[Opponent's Turn] All of your other Digimon with [Vegetation], [Plant], or [Fairy] in one of their traits gain \"[On Deletion] Gain 2 memory, and return 1 Digimon card with 3000 DP or less from your trash to your hand.\""

class BT10_057 extends Card:
	func _init():
		name = "BloomLordmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.SR
		id = "BT10-057"
		play_cost = 12
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Fairy"
		power = 12000
		effect_text = "[When Digivolving] You may suspend 1 of your Digimon. Then, gain 1 memory for each suspended Digimon with [Vegetation], [Plant], or [Fairy] in one of their traits you have in play. If you gain 2 or more memory by this effect, unsuspend this Digimon and it gains <Piercing> (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would) for the turn.\n[Your Turn] For every 2 suspended Digimon you have in play, this Digimon gets +2000 DP and gains <Security Attack +1> (This Digimon checks 1 additional security card)."

class BT10_058 extends Card:
	func _init():
		name = "Monitamon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT10-058"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = ""
		digimon_type = "CRT/Twilight/Xros Heart"
		power = 2000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 2 cards that are either black with [Knightmon], or [DeadlyAxemon] in their names or with [Twilight] in their traits among them to your hand. Place the rest at the bottom of your deck in any order."

class BT10_059 extends Card:
	func _init():
		name = "Spadamon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "BT10-059"
		play_cost = 4
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digivolve_color_2 = ""
		digivolve_cost_2 = 1
		digivolve_level_2 = 2
		digimon_type = "Weapon/Legend-Arms/Xros Heart"
		power = 2000
		effect_text = "[On Play] By placing this Digimon under 1 of your Digimon with [Legend-Arms], or [Xros Heart] in its traits as its bottom digivolution card, <De-Digivolve  1> on 1 of your opponent's Digimon (Trash up to 1 card from the top of one of your opponent's Digimon. If it has no digivolution cards, or becomes a level 3 Digimon, you can't trash any more cards)."
		inherited_effect_text = "[When Attacking] (Once Per Turn) Reveal the top 3 cards of your deck. Add 1 card with [Legend-Arms], or [Xros Heart] in its traits among them to your hand. Place the rest at the bottom of your deck in any order."

class BT10_060 extends Card:
	func _init():
		name = "Sparrowmon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "BT10-060"
		play_cost = 4
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Bird/Twilight/Xros Heart"
		power = 2000
		effect_text = "[All Turns] While you have another Digimon or Tamer with [Xros Heart], or [Twilight] in its traits in play, this Digimon gets +3000 DP.\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[Opponent's Turn] While this Digimon has [Shoutmon], or [Mervamon] in its name, it gains <Reboot> (Unsuspend this Digimon during your opponent's unsuspend phase)."

class BT10_061 extends Card:
	func _init():
		name = "SkullKnightmon: Mighty Axe Mode"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT10-061"
		play_cost = 4
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Enhancement/Twilight"
		power = 4000
		effect_text = "This card/Digimon is also treated as if its name is [SkullKnightmon] and [DeadlyAxemon].\n[On Play] Reveal the top 3 cards of your deck. Add 1 card with [Knightmon] in its name or 1 [DeadlyAxemon] or [Nene Amano] among them to your hand. Trash the rest. Then, if DigiXrosing with 2 cards, delete 1 of your opponent's Digimon with a play cost of 4 or less."

class BT10_062 extends Card:
	func _init():
		name = "Golemon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT10-062"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Mineral"
		power = 5000

class BT10_063 extends Card:
	func _init():
		name = "Hi-VisionMonitamon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT10-063"
		play_cost = 6
		level = 4
		stage_level = Stage.HYBRID
		attribute = ""
		digimon_type = "LCD/Twilight/Xros Heart"
		power = 7000

class BT10_064 extends Card:
	func _init():
		name = "Gogmamon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT10-064"
		play_cost = 8
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Rock"
		power = 8000

class BT10_065 extends Card:
	func _init():
		name = "Assaultmon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT10-065"
		play_cost = 7
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Cyborg"
		power = 1000

class BT10_066 extends Card:
	func _init():
		name = "DarkKnightmon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "BT10-066"
		play_cost = 8
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Dark Knight/Twilight"
		power = 7000
		effect_text = "[On Play] <De-Digivolve  1> on 1 of your opponent's Digimon (Trash up to 1 card from the top of one of your opponent's Digimon. If it has no digivolution cards, or becomes a level 3 Digimon, you can't trash any more cards) of your opponent's Digimon. Then, if DigiXrosing with 2 cards, delete 1 of your opponent's Digimon with a play cost of 5 or less.\n[All Turns] When this Digimon would be deleted, by returning 1 black level 4 or lower Digimon card from this Digimon's digivolution cards to its owner's hand, you may play 1 [SkullKnightmon] from this Digimon's digivolution cards without paying its memory cost."

class BT10_067 extends Card:
	func _init():
		name = "Justimon: Critical Arm"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "BT10-067"
		play_cost = 11
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Cyborg"
		power = 11000
		effect_text = "[When Digivolving] By returning 1 non-[Justimon: Critical Arm] Digimon card with [Justimon] in its name from this Digimon's digivolution cards to its owner's hand, delete 1 of your opponent's Digimon with a play cost of 9 or less.\n[When Attacking] If you have a Tamer in play, may digivolve this Digimon into a non-[Justimon: Critical Arm] Digimon card with [Justimon] in its name for a memory cost of 2, ignoring its digivolution requirements."

class BT10_068 extends Card:
	func _init():
		name = "Gankoomon (X Antibody)"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.SR
		id = "BT10-068"
		play_cost = 13
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color_2 = ""
		digivolve_cost_2 = 4
		digivolve_level_2 = 5
		digimon_type = "Holy Warrior/Royal Knight/X Antibody"
		power = 12000
		effect_text = "<Blocker> (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead).\n[When Digivolving] You may play 1 Digimon card with [Sistermon] in its name from your hand or trash without paying its memory cost. Then, if [Gankoomon] is in this Digimon's digivolution cards or you have a Digimon with [Sistermon] in its name in play, until the end of your opponent's turn, all of your Digimon get +2000 DP and your opponent's effects can't return them to hands or decks or reduce their DP."

class BT10_069 extends Card:
	func _init():
		name = "DarkKnightmon (X Antibody)"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.SR
		id = "BT10-069"
		play_cost = 13
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digivolve_color_2 = ""
		digivolve_cost_2 = 5
		digivolve_level_2 = 5
		digimon_type = "Dark Knight/X Antibody"
		power = 12000
		effect_text = "[When Digivolving] Return 1 black or purple Digimon card other than [DarkKnightmon (X Antibody)] from your trash to your hand. Then, if [DarkKnightmon] is in this Digimon's digivolution cards, delete 1 Tamer, and unsuspend this Digimon.\n[On Deletion] You may play 1 [DarkKnightmon] from your trash without paying its memory cost."

class BT10_070 extends Card:
	func _init():
		name = "Blastmon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "BT10-070"
		play_cost = 13
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digimon_type = "Mineral/Bagra Army"
		power = 1300
		effect_text = "<Rush> (This Digimon can attack the turn it comes into play).\n[On Play] If this Digimon has 3 digivolution cards, <Blitz> (If your opponent has 1 or more memory, this Digimon may attack).\n[Opponent's Turn] (Once Per Turn) When an opponent's Digimon attacks, by trashing 1 of this Digimon's digivolution cards, delete 1 of your opponent's level 4 or lower Digimon."
		ruling = [
					"Q: Does this card have <Blitz> in the deck, when revealed by [BT5-009 Shoutmon]?",
					"A: No, it does not.",
					"Q: If this Digimon has [BT5-014 OmniShoutmon], does this Digimon gain <Security Attack +1>?",
					"A: Only if it has 3 digivolution cards, but the check will ignore the [On Play].",
]

class BT10_071 extends Card:
	func _init():
		name = "Gazimon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT10-071"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Mammal"
		power = 2000
		inherited_effect_text = "[All Turns] While there are 10 or more cards in your trash, this Digimon gains <Retaliation> (When this Digimon is deleted after losing a battle, delete the Digimon it was battling)."

class BT10_072 extends Card:
	func _init():
		name = "Soundbirdmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT10-072"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Avian"
		power = 1000
		effect_text = "[When Attacking] By placing 1 purple Digimon card from your hand under one of your Tamers, <Draw 1> (Draw 1 card from your deck).\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[Opponent's Turn] When this card is trashed from digivolution cards by an effect, gain 1 memory."

class BT10_073 extends Card:
	func _init():
		name = "ChuuChuumon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT10-073"
		play_cost = 4
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Beast/Bagra Army"
		power = 1000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon card with [Bagra Army] in its traits and 1 [Ewan Amano] among them to your hand. Place the rest at the bottom of your deck in any order.\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[Opponent's Turn] When this card is trashed from digivolution cards by an effect, gain 1 memory."

class BT10_074 extends Card:
	func _init():
		name = "Quetzalmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT10-074"
		play_cost = 4
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digimon_type = "Mythical Beast"
		power = 4000
		effect_text = "<Armor Purge>  (When this Digimon would be deleted, you may trash the top card of this Digimon to prevent that deletion)."

class BT10_075 extends Card:
	func _init():
		name = "Damemon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT10-075"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Mutant/Bagra Army"
		power = 4000
		effect_text = "[On Play] [When Digivolving] If you don't have an [Ewan Amano] in play, you may play one from your hand without paying its memory cost.\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[Opponent's Turn] When this card is trashed from digivolution cards by an effect, gain 1 memory."

class BT10_076 extends Card:
	func _init():
		name = "Troopmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT10-076"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Undead/Bagra Army"
		power = 4000
		effect_text = "[Opponent's Turn] (Once Per Turn) When an opponent plays a Digimon or Tamer, by choosing and trashing 1 of this Digimon's digivolution cards, gain 1 memory.\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[Opponent's Turn] When this card is trashed from digivolution cards by an effect, gain 1 memory."

class BT10_077 extends Card:
	func _init():
		name = "MadLeomon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT10-077"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Undead/Bagra Army"
		power = 4000
		effect_text = "[Opponent's Turn] (Once Per Turn) When an effect adds cards to your opponent's hand, by choosing and trashing 1 of this Digimon's digivolution cards, your opponent trashes cards from their hand equal to the number of cards added to their hand by the effect.\n[On Deletion] <Save> (You may place this card under one of your Tamers)."
		inherited_effect_text = "[Opponent's Turn] When this card is trashed from digivolution cards by an effect, gain 1 memory."

class BT10_078 extends Card:
	func _init():
		name = "GulusGammamon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.R
		id = "BT10-078"
		play_cost = 6
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Dragonkin"
		power = 6000
		effect_text = "[All Turns]  While this Digimon's digivolution cards include a card with [Gammamon] in its name, this Digimon gains <Retaliation> (When this Digimon is deleted after losing a battle, delete the Digimon it was battling).\n[On Deletion] You may play 1 [Gammamon] from your trash suspended without paying its memory cost."

class BT10_079 extends Card:
	func _init():
		name = "Sandiramon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT10-079"
		play_cost = 5
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Holy Beast/Deva"
		power = 6000

class BT10_080 extends Card:
	func _init():
		name = "SkullBaluchimon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT10-080"
		play_cost = 7
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Undead/X Antibody"
		power = 7000
		effect_text = "When this card is trashed from your hand by one of your effects, if it's your turn, you may digivolve 1 of your Digimon into 1 purple Digimon card with [Undead], or [Dark Animal] in its traits from your trash for its digivolution cost.\n[When Digivolving] If digivolving from the trash, this Digimon gains \"[On Deletion] delete 1 of your opponent's Digimon.\" until the end of your opponent's turn."

class BT10_081 extends Card:
	func _init():
		name = "Baalmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT10-081"
		play_cost = 7
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.FREE
		digimon_type = "Wizard/Bagra Army"
		power = 7000
		effect_text = "[When Attacking] You may trash up to 3 cards from the top of your deck.\n[On Deletion] If you have 10 or more cards in your trash, you may play 1 [Beelzemon] from your trash without paying its memory cost."

class BT10_082 extends Card:
	func _init():
		name = "Beelzemon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT10-082"
		play_cost = 11
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Demon Lord/Xros Heart"
		power = 11000
		effect_text = "[On Play] [When Digivolving] You may trash 3 cards from the top of your deck. Then, for every 10 cards in your trash, delete 1 of your opponent's level 4 or lower Digimon."
		inherited_effect_text = "[End of Attack] (Once Per Turn) For every 10 cards in your trash, gain 1 memory."

class BT10_083 extends Card:
	func _init():
		name = "Minervamon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.SR
		id = "BT10-083"
		play_cost = 12
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.VIRUS
		digimon_type = "Shaman/Olympos XII"
		power = 11000
		effect_text = "<Retaliation> (When this Digimon is deleted after losing a battle, delete the Digimon it was battling).\n[Opponent's Turn] When your opponent plays a Digimon, you may plays 1 purple level 4 or lower Digimon card from your trash without paying its memory cost. Any [On Play] effects on Digimon played with this effect don't activate.\n[On Deletion] If your opponent has 2 or fewer Digimon in play, you may play 1 purple level 5 or lower Digimon card or 1 [Mervamon] from your trash without paying its memory cost."

class BT10_084 extends Card:
	func _init():
		name = "Tactimon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT10-084"
		play_cost = 13
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Wizard/Bagra Army"
		power = 12000
		effect_text = "[On Play] You may play 2 level 4 or lower Digimon cards with [Bagra Army] in their traits from your trash without paying their memory costs. All Digimon played by this effect gain <Blocker> (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead) until the end of your opponent's turn.\n[Opponent's Turn] When a digivolution card of one of your other Digimon would be trashed by an effect, you may trash one of this Digimon's digivolution cards instead."

class BT10_085 extends Card:
	func _init():
		name = "Sistermon Ciel"
		type = Type.DIGIMON
		color = ColorGroup.WHITE
		rarity = Rarity.R
		id = "BT10-085"
		play_cost = 4
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Puppet"
		power = 5000
		effect_text = "[On Play] If it's your turn, you may digivolve 1 of your Digimon into a Digimon card with [Royal Knight] in its traits in your hand for its digivolution cost.\n[Your Turn] (Once Per Turn) When one of your Digimon digivolves into a Digimon with [Huckmon] in its name or [Royal Knight] in its traits , gain 1 memory."

class BT10_086 extends Card:
	func _init():
		name = "Omnimon (X Antibody)"
		type = Type.DIGIMON
		color = ColorGroup.WHITE
		rarity = Rarity.SR
		id = "BT10-086"
		play_cost = 16
		level = 7
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digivolve_color_2 = ""
		digivolve_cost_2 = 7
		digivolve_level_2 = 6
		digimon_type = "Holy Warrior/Royal Knight/X Antibody"
		power = 16000
		effect_text = "When a Digimon with [X Antibody] in its digivolution cards would digivolve into this card, reduce the digivolution cost by 2.\n[When Digivolving] Return all of your opponent's Digimon with the highest level to the bottom of their owners' decks in any order.\n[When Digivolving] [When Attacking] (Once Per Turn) By placing 1 [X Antibody] or level 6 card from this Digimon's digivolution cards at the bottom of its owner's deck, reveal all of your opponent's security cards, and trash 1 of them. Place the rest in your opponent's security stack face down. Then, your opponent shuffles their security stack."
		notes = "Omegamon X Antibody"

class BT10_087 extends Card:
	func _init():
		name = "Mikey Kudo"
		type = Type.TAMER
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT10-087"
		play_cost = 3
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 card with [Xros Heart] in its traits among them to your hand, and place 1 Digimon card with [Xros Heart] in its traits under this tamer. Place the rest at the bottom of your deck in any order.\n[Your Turn] When you would play a Digimon with DigiXros requirements, by suspending this Tamer, you may place cards from under your Tamers as digivolution cards for a DigiXros."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Kudo Taiki"

class BT10_088 extends Card:
	func _init():
		name = "Christopher Aonuma"
		type = Type.TAMER
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT10-088"
		play_cost = 4
		effect_text = "[Start of Your Turn] If you have 2 memory or less, set your memory to 3.\n[Your Turn] When you would play a Digimon with DigiXros requirements, by suspending this Tamer, you may place cards from under your Tamers as digivolution cards for a DigiXros."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Aonuma Kiriha"

class BT10_089 extends Card:
	func _init():
		name = "Angie Hinomoto"
		type = Type.TAMER
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "BT10-089"
		play_cost = 3
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Hinomoto Akari"

class BT10_090 extends Card:
	func _init():
		name = "Jeremy Tsurugi"
		type = Type.TAMER
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "BT10-090"
		play_cost = 3
		effect_text = "[On Play] You may play 1 [Ballistamon] from your hand or from under one of your Tamers without paying its memory cost.\n[Your Turn] When you play a Digimon with [Xros Heart] in its traits, by suspending this Tamer, gain 1 memory."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Tsurugi Zenjiro"

class BT10_091 extends Card:
	func _init():
		name = "Ruli Tsukiyono"
		type = Type.TAMER
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "BT10-091"
		play_cost = 4
		effect_text = "[Start of Your Turn] If you have 2 memory or less, set your memory to 3.\n[Your Turn] When you attack with a Digimon that has [Angoramon] in its name or is level 5 or higher, you may suspend this Tamer to suspend 1 of your opponent's Digimon with 5000 DP or less."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		notes = "Tsukiyono Ruli"

class BT10_092 extends Card:
	func _init():
		name = "Nene Amano"
		type = Type.TAMER
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "BT10-092"
		play_cost = 3
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 card with [Knightmon], or [DeadlyAxemon] in its name or [Twilight] in its traits among them to your hand. Place the rest at the bottom of your deck in any order.\n[Opponent's Turn] All of your Digimon with h [DarkKnightmon] in their names or [Twilight] in their traits gain <Blocker> (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead).\n[On Deletion] Gain 2 memory."
		sec_effect_text = "[Security] Play this card without paying its memory cost."

class BT10_093 extends Card:
	func _init():
		name = "Ewan Amano"
		type = Type.TAMER
		color = ColorGroup.PURPLE
		rarity = Rarity.R
		id = "BT10-093"
		play_cost = 3
		effect_text = "[All Turns] (Once Per Turn) When a purple card is placed under this Tamer, <Draw 1> (Draw 1 card from your deck).\n[Your Turn] (Once Per Turn) When you would play a level 4 or higher Digimon card with  [Bagra Army] in its traits, by placing up to 3 purple Digimon cards from under your Tamers in the digivolution cards of the Digimon card played, reduce the memory cost of that Digimon by 2 for each card placed."
		sec_effect_text = "[Security] Play this card without paying its memory cost."

class BT10_094 extends Card:
	func _init():
		name = "Breaclaw"
		type = Type.OPTION
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "BT10-094"
		play_cost = 1
		effect_text = "[Main] 1 of your Digimon gets +2000 DP for the turn. Then, by placing 1 Digimon card with [Gammamon] in its name from your hand under 1 of your Digimon as its bottom digivolution card, <Draw 1> (Draw 1 card from your deck)."
		sec_effect_text = "[Security] You may play 1 [Gammamon] from your hand or trash without paying its memory cost."

class BT10_095 extends Card:
	func _init():
		name = "Hero of the Skies!"
		type = Type.OPTION
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "BT10-095"
		play_cost = 5
		effect_text = "[Main] Activate 1 of the effects below. If you have a Digimon with [Shoutmon X5] in its name in play, activate all of the effects below instead.\n・1 of your Digimon with [Xros Heart] in its traits gains <Security Attack +1> (This Digimon checks 1 additional security card) for the turn.\n・<Draw 2> (Draw 2 cards from your deck)."
		sec_effect_text = "[Security] Add this card to its owner's hand."

class BT10_096 extends Card:
	func _init():
		name = "Burning Star Crusher"
		type = Type.OPTION
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "BT10-096"
		play_cost = 4
		effect_text = "[Main] Choose 1 of your level 4 or higher Digimon with [Shoutmon] in its name. Delete 1 of your opponent's Digimon with DP less than or equal to the chosen Digimon."
		sec_effect_text = "[Security] Reveal the top 3 cards of your deck. Add 1 Digimon card card with [Xros Heart] in its traits among them to your hand, and you may play 1 [Mikey Kudo] among them without paying its memory cost. Place the rest at the bottom of your deck in any order."

class BT10_097 extends Card:
	func _init():
		name = "Blazing Memory Boost!"
		type = Type.OPTION
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "BT10-097"
		play_cost = 5
		effect_text = "[Main] Reveal the top 6 cards of your deck. Add 2 cards with [Blue Flare] in their traits among them to your hand, and you may play 1 [Christopher Aonuma] among them without paying its memory cost. Place the rest at the bottom of your deck in any order. Then, place this card in your Battle Area.\n[Main] <Delay> (Trash this card in your battle area to activate the effect below. You can't activate this effect the turn this card enters play.)\n・Gain 2 memory."
		sec_effect_text = "[Security] Place this card in its owner's battle area."

class BT10_098 extends Card:
	func _init():
		name = "Plasma Deckerdra Launcher"
		type = Type.OPTION
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "BT10-098"
		play_cost = 7
		effect_text = "When you would use this card, if your opponent has 2 or more Digimon in play, reduce the memory cost by 2.\n[Main] Return 1 of your opponent's level 6 or higher Digimon to its owner's hand."
		sec_effect_text = "[Security] Return 1 of your opponent's Digimon to its owner's hand."

class BT10_099 extends Card:
	func _init():
		name = "Healing Therapy"
		type = Type.OPTION
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT10-099"
		play_cost = 2
		effect_text = "[Main] Until the end of your opponent's turn, 1 of your opponent's Digimon gains <Security Attack -1> (This Digimon checks 1 fewer security card). If you have a [Venusmon] in play, 3 of your opponent's Digimon gain it instead."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class BT10_100 extends Card:
	func _init():
		name = "Impulse Memory Boost!"
		type = Type.OPTION
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "BT10-100"
		play_cost = 3
		effect_text = "[Main] You may play 1 [Pulsemon] from your hand without paying its memory cost. Then, place this card in your Battle Area.\n[Main] <Delay> (Trash this card in your battle area to activate the effect below. You can't activate this effect the turn this card enters play.)\n・Gain 2 memory."
		sec_effect_text = "[Security] Place this card in its owner's battle area."

class BT10_101 extends Card:
	func _init():
		name = "Lónkhē Adistakto"
		type = Type.OPTION
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "BT10-101"
		play_cost = 8
		effect_text = "While you have a [Pulsemon] or a Digimon with [Pulsemon] in its digivolution cards in play, you may use this card without meeting its color requirements.\n[Main] If you have 3 or more security cards, 1 of your opponent's Digimon gets -12000 DP for the turn. If you have 3 or fewer security cards, place 1 of your opponent's Digimon face down on top of their security stack."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class BT10_102 extends Card:
	func _init():
		name = "Pyon Dump"
		type = Type.OPTION
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "BT10-102"
		play_cost = 2
		effect_text = "[Main] 1 of your Digimon gains <Piercing> (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would) for the turn. Then, if you have a Digimon in play with [Angoramon] in its name or with [Angoramon] in its digivolution cards, suspend 1 of your opponent's Digimon."
		sec_effect_text = "[Security] Suspend 1 of your opponent's Digimon. Then, add this card to your hand."

class BT10_103 extends Card:
	func _init():
		name = "Gran del Sol"
		type = Type.OPTION
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "BT10-103"
		play_cost = 8
		effect_text = "When you would use this card, if you have 2 or more suspended green Digimon in play, reduce the memory cost by 2.\n[Main] Suspend 1 of your opponent's Digimon. Then, return 1 of your opponent's suspended Digimon to the bottom of its owner's deck."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class BT10_104 extends Card:
	func _init():
		name = "Immortal Ruler"
		type = Type.OPTION
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "BT10-104"
		play_cost = 0
		effect_text = "While you have a [Nene Amano] in play, you may use this card without meeting its color requirements.\n[Main] Trash 3 cards from the top of your deck. Then, you may play 1 [DarkKnightmon] from your trash for its memory cost. If you play a Digimon card with DigiXros requirements by this effect, you may DigiXros by placing any of the specified Digimon from your trash at the bottom of this card as digivolution cards."
		sec_effect_text = "[Security] Add this card to its owner's hand."

class BT10_105 extends Card:
	func _init():
		name = "Defense Plug-In C"
		type = Type.OPTION
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "BT10-105"
		play_cost = 5
		effect_text = "While you have a Tamer in play, you may use this card without meeting its color requirements.\n[Main] Until the end of your opponent's turn, 1 of your Digimon gains <Blocker> (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead), <Reboot> (Unsuspend this Digimon during your opponent's unsuspend phase), and can't be deleted by your opponent's effects."
		sec_effect_text = "[Security] Reveal the top 3 cards of your deck. You may play 1 Digimon card with a play cost of 4 or less among them without paying its memory cost. Place the rest at the bottom of your deck in any order. Then, add this card to its owner's hand."

class BT10_106 extends Card:
	func _init():
		name = "Justice Kick"
		type = Type.OPTION
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "BT10-106"
		play_cost = 12
		effect_text = "When you would use this card, reduce its memory cost by 1 for each Tamer you have in play.\n[Main] You may play 1 Digimon card with [Justimon] in its name from your hand without paying its memory cost. If you do, delete 1 of your opponent's Digimon with a play cost less than or equal to the Digimon you played."
		sec_effect_text = "[Security] You may play 1 black Tamer card from your hand without paying its memory cost. Then, add this card to its owner's hand."

class BT10_107 extends Card:
	func _init():
		name = "Buzzing Fist"
		type = Type.OPTION
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "BT10-107"
		play_cost = 2
		effect_text = "[Main] Reveal the top 3 cards of your deck. Add up to 1 card with [Bagra Army] in its traits among them to your hand. Trash the rest. Then, you may place 1 Digimon card with [Bagra Army] in its traits from your trash under one of your Tamers."
		sec_effect_text = "[Security] You may play 1 [Ewan Amano] from your hand or trash without paying its memory cost. Then, add this card to its owner's hand."
		notes = "Bun Bun Punch"

class BT10_108 extends Card:
	func _init():
		name = "Death the Cannon"
		type = Type.OPTION
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "BT10-108"
		play_cost = 8
		effect_text = "When this card is trashed from your deck, return it to your hand.\n[Main] Delete 1 of your opponent's level 6 or lower Digimon. If there are 10 or more cards in your trash, add 1 to the level of the Digimon you can select with this effect."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class BT10_109 extends Card:
	func _init():
		name = "Upgrade Plug-In O"
		type = Type.OPTION
		color = ColorGroup.WHITE
		rarity = Rarity.U
		id = "BT10-109"
		play_cost = 2
		effect_text = "While you have a Tamer in play, you may use this card without meeting its color requirements.\n[Main] 1 of your Digimon gets +3000 DP until the end of your opponent's turn."
		sec_effect_text = "[Security] Gain 1 memory and add this card to its owner's hand."

class BT10_110 extends Card:
	func _init():
		name = "Seiken Meppa"
		type = Type.OPTION
		color = ColorGroup.WHITE
		rarity = Rarity.SEC
		id = "BT10-110"
		play_cost = 3
		effect_text = "While you have a Digimon with [Royal Knight] in its traits in play, you may use this card without meeting its color requirements.\n[Main] Unsuspend 1 of your Digimon. Then, if that Digimon is [Jesmon GX], activate 1 of its [When Digivolving] effects."
		sec_effect_text = "[Security] Add this card to its owner's hand."

class BT10_111 extends Card:
	func _init():
		name = "Shoutmon (King Version)"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.SEC
		id = "BT10-111"
		play_cost = 5
		level = 4
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digimon_type = "Mini Dragon/Xros Heart"
		power = 4000
		effect_text = "This card/Digimon is also treated as if its name is [Shoutmon].\n[On Play] You may return 1 card with a DigiXros requirement from your trash to your hand. When you would DigiXros this turn, this Digimon may replace 1 of the DigiXros requirements.\n<Material Save 1> (When this Digimon would be deleted, you may place 1 card in this Digimon's DigiXros requirements from this Digimon's digivolution cards under 1 of your Tamers."
		inherited_effect_text = "[Your Turn] While this Digimon has [Shoutmon] in its name, it gets +2000 DP."

class BT10_112 extends Card:
	func _init():
		name = "Jesmon GX"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.SEC
		id = "BT10-112"
		play_cost = 15
		level = 7
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color_2 = ""
		digivolve_cost_2 = 5
		digivolve_level_2 = 6
		digimon_type = "Holy Warrior/Royal Knight/X Antibody"
		power = 15000
		effect_text = "[When Digivolving] You may place 1 card with [Royal Knight] in its traits and a play cost of 13 or less from your hand or trash under this Digimon as its bottom digivolution card. Activate 1 of that Digimon's [When Digivolving] effects as if it was one of this Digimon's effects. Then, <Blitz> (If your opponent has 1 or more memory, this Digimon may attack).\n[All Turns] While a card with [Royal Knight] in its traits is in this Digimon's digivolution cards, this Digimon gains <Piercing> (When this Digimon attacks and deletes an opponent's Digimon and survives the battle, it performs any security checks it normally would) and <Blocker> (When an opponent's Digimon attacks, you may suspend this Digimon to force the opponent to attack it instead), and gains <Security Attack +1> (This Digimon checks 1 additional security card) for each card with [Royal Knight] in its traits in this Digimon's digivolution cards."

