# Content autogenerated. Data from digimoncardgame.fandom.com

static func register_cards():

	CardDB.register_booster("EX-01", "EX-01: Classic Collection")
	CardDB.add_card(EX1_001.new())
	CardDB.add_card(EX1_001_B.new())
	CardDB.add_card(EX1_002.new())
	CardDB.add_card(EX1_003.new())
	CardDB.add_card(EX1_004.new())
	CardDB.add_card(EX1_004_B.new())
	CardDB.add_card(EX1_005.new())
	CardDB.add_card(EX1_005_B.new())
	CardDB.add_card(EX1_006.new())
	CardDB.add_card(EX1_006_B.new())
	CardDB.add_card(EX1_007.new())
	CardDB.add_card(EX1_008.new())
	CardDB.add_card(EX1_008_B.new())
	CardDB.add_card(EX1_009.new())
	CardDB.add_card(EX1_009_B.new())
	CardDB.add_card(EX1_010.new())
	CardDB.add_card(EX1_010_B.new())
	CardDB.add_card(EX1_011.new())
	CardDB.add_card(EX1_011_B.new())
	CardDB.add_card(EX1_012.new())
	CardDB.add_card(EX1_012_B.new())
	CardDB.add_card(EX1_013.new())
	CardDB.add_card(EX1_014.new())
	CardDB.add_card(EX1_015.new())
	CardDB.add_card(EX1_015_B.new())
	CardDB.add_card(EX1_016.new())
	CardDB.add_card(EX1_017.new())
	CardDB.add_card(EX1_018.new())
	CardDB.add_card(EX1_019.new())
	CardDB.add_card(EX1_019_B.new())
	CardDB.add_card(EX1_020.new())
	CardDB.add_card(EX1_021.new())
	CardDB.add_card(EX1_021_B.new())
	CardDB.add_card(EX1_022.new())
	CardDB.add_card(EX1_023.new())
	CardDB.add_card(EX1_024.new())
	CardDB.add_card(EX1_024_B.new())
	CardDB.add_card(EX1_025.new())
	CardDB.add_card(EX1_026.new())
	CardDB.add_card(EX1_026_B.new())
	CardDB.add_card(EX1_027.new())
	CardDB.add_card(EX1_028.new())
	CardDB.add_card(EX1_029.new())
	CardDB.add_card(EX1_029_B.new())
	CardDB.add_card(EX1_030.new())
	CardDB.add_card(EX1_030_B.new())
	CardDB.add_card(EX1_031.new())
	CardDB.add_card(EX1_032.new())
	CardDB.add_card(EX1_033.new())
	CardDB.add_card(EX1_033_B.new())
	CardDB.add_card(EX1_034.new())
	CardDB.add_card(EX1_035.new())
	CardDB.add_card(EX1_036.new())
	CardDB.add_card(EX1_037.new())
	CardDB.add_card(EX1_038.new())
	CardDB.add_card(EX1_039.new())
	CardDB.add_card(EX1_039_B.new())
	CardDB.add_card(EX1_040.new())
	CardDB.add_card(EX1_041.new())
	CardDB.add_card(EX1_042.new())
	CardDB.add_card(EX1_043.new())
	CardDB.add_card(EX1_043_B.new())
	CardDB.add_card(EX1_044.new())
	CardDB.add_card(EX1_045.new())
	CardDB.add_card(EX1_046.new())
	CardDB.add_card(EX1_047.new())
	CardDB.add_card(EX1_048.new())
	CardDB.add_card(EX1_049.new())
	CardDB.add_card(EX1_050.new())
	CardDB.add_card(EX1_051.new())
	CardDB.add_card(EX1_052.new())
	CardDB.add_card(EX1_053.new())
	CardDB.add_card(EX1_054.new())
	CardDB.add_card(EX1_055.new())
	CardDB.add_card(EX1_056.new())
	CardDB.add_card(EX1_057.new())
	CardDB.add_card(EX1_058.new())
	CardDB.add_card(EX1_059.new())
	CardDB.add_card(EX1_060.new())
	CardDB.add_card(EX1_061.new())
	CardDB.add_card(EX1_062.new())
	CardDB.add_card(EX1_063.new())
	CardDB.add_card(EX1_063_B.new())
	CardDB.add_card(EX1_064.new())
	CardDB.add_card(EX1_065.new())
	CardDB.add_card(EX1_065_B.new())
	CardDB.add_card(EX1_066.new())
	CardDB.add_card(EX1_066_B.new())
	CardDB.add_card(EX1_067.new())
	CardDB.add_card(EX1_068.new())
	CardDB.add_card(EX1_069.new())
	CardDB.add_card(EX1_070.new())
	CardDB.add_card(EX1_071.new())
	CardDB.add_card(EX1_072.new())
	CardDB.add_card(EX1_073.new())
	CardDB.add_card(EX1_073_B.new())

class EX1_001 extends Card:
	func _init():
		name = "Agumon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "EX1-001"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Reptile"
		power = 2000
		inherited_effect_text = "[When Attacking] [Once Per Turn] Reveal the top 3 cards of your deck. Add 1 Tamer card or 1 Digimon Card with [Agumon] among them to your hand. Place the remaining cards at the bottom of your deck in any order."

class EX1_001_B extends Card:
	func _init():
		name = "Agumon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "EX1-001 (B)"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Reptile"
		power = 2000
		inherited_effect_text = "[When Attacking] [Once Per Turn] Reveal the top 3 cards of your deck. Add 1 Tamer card or 1 Digimon Card with [Agumon] among them to your hand. Place the remaining cards at the bottom of your deck in any order."
		is_parallel = true
		notes = "parallel promo"

class EX1_002 extends Card:
	func _init():
		name = "Biyomon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "EX1-002"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Bird"
		power = 2000
		effect_text = "[When Attacking] [Once Per Turn] When this Digimon attacks a player, trigger [Draw 1]."
		notes = "Piyomon"

class EX1_003 extends Card:
	func _init():
		name = "Birdramon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "EX1-003"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Giant Bird"
		power = 5000
		effect_text = "[When Attacking] When this Digimon attacks a player, delete 1 of your opponent's Digimon with 3000 DP or less."

class EX1_004 extends Card:
	func _init():
		name = "Greymon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "EX1-004"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Dinosaur"
		power = 5000
		inherited_effect_text = "[When Attacking] [Once Per Turn] You may play 1 [Tai Kamiya] with a play cost of 3 or less from your hand without paying its memory cost."

class EX1_004_B extends Card:
	func _init():
		name = "Greymon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "EX1-004 (B)"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Dinosaur"
		power = 5000
		inherited_effect_text = "[When Attacking] [Once Per Turn] You may play 1 [Tai Kamiya] with a play cost of 3 or less from your hand without paying its memory cost."
		is_parallel = true
		notes = "parallel promo"

class EX1_005 extends Card:
	func _init():
		name = "Tyrannomon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "EX1-005"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.RED
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Dinosaur"
		power = 4000
		effect_text = "[When Digivolved] If you don't have a [Taiga] in play, you may play one from your hand without paying its memory cost.\n[Your Turn] This Digimon is also treated as green."
		inherited_effect_text = "[Your Turn] While this Digimon has [Tyrannomon], it gets +2000 DP."

class EX1_005_B extends Card:
	func _init():
		name = "Tyrannomon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "EX1-005 (B)"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.RED
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Dinosaur"
		power = 4000
		effect_text = "[When Digivolved] If you don't have a [Taiga] in play, you may play one from your hand without paying its memory cost.\n[Your Turn] This Digimon is also treated as green."
		inherited_effect_text = "[Your Turn] While this Digimon has [Tyrannomon], it gets +2000 DP."
		is_parallel = true
		notes = "parallel promo"

class EX1_006 extends Card:
	func _init():
		name = "Garudamon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "EX1-006"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Birdkin"
		power = 7000
		inherited_effect_text = "[When Attacking] [Once Per Turn] When this Digimon attacks a player, gain 1 memory."

class EX1_006_B extends Card:
	func _init():
		name = "Garudamon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "EX1-006 (B)"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Birdkin"
		power = 7000
		inherited_effect_text = "[When Attacking] [Once Per Turn] When this Digimon attacks a player, gain 1 memory."
		is_parallel = true
		notes = "parallel promo"

class EX1_007 extends Card:
	func _init():
		name = "Megadramon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.C
		id = "EX1-007"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.BLACK
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Cyborg"
		power = 7000
		effect_text = "[On Play] Delete up to 2 of your opponent's Digimon with 3000 DP or less."
		inherited_effect_text = "[Your Turn] While this Digimon has [Machine], it gains [Security Attack +1]."

class EX1_008 extends Card:
	func _init():
		name = "MetalGreymon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "EX1-008"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.BLACK
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Cyborg"
		power = 7000
		effect_text = "[When Attacking] When this Digimon attacks a player, delete 1 of your opponent's Digimon with 4000 DP or less."
		inherited_effect_text = "[Your Turn] While this Digimon has [Machine], it gains [Piercing]."

class EX1_008_B extends Card:
	func _init():
		name = "MetalGreymon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "EX1-008 (B)"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.BLACK
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Cyborg"
		power = 7000
		effect_text = "[When Attacking] When this Digimon attacks a player, delete 1 of your opponent's Digimon with 4000 DP or less."
		inherited_effect_text = "[Your Turn] While this Digimon has [Machine], it gains [Piercing]."
		is_parallel = true
		notes = "parallel promo"

class EX1_009 extends Card:
	func _init():
		name = "WarGreymon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.SR
		id = "EX1-009"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Dragonkin"
		power = 12000
		effect_text = "[When Digivolved] [Blitz]\n[When Attacking] When this Digimon attacks a player, if you have a Tamer in play, delete 1 of your opponent's Digimon with [Blocker]."

class EX1_009_B extends Card:
	func _init():
		name = "WarGreymon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.SR
		id = "EX1-009 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Dragonkin"
		power = 12000
		effect_text = "[When Digivolved] [Blitz]\n[When Attacking] When this Digimon attacks a player, if you have a Tamer in play, delete 1 of your opponent's Digimon with [Blocker]."
		is_parallel = true
		notes = "parallel promo"

class EX1_010 extends Card:
	func _init():
		name = "Phoenixmon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "EX1-010"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Holy Beast"
		power = 11000
		effect_text = "[Security Attack +1]\n[When Attacking] When this Digimon attacks a player, trigger [Draw 2]."
		notes = "Hououmon"

class EX1_010_B extends Card:
	func _init():
		name = "Phoenixmon"
		type = Type.DIGIMON
		color = ColorGroup.RED
		rarity = Rarity.U
		id = "EX1-010 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.RED
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Holy Beast"
		power = 11000
		effect_text = "[Security Attack +1]\n[When Attacking] When this Digimon attacks a player, trigger [Draw 2]."
		is_parallel = true
		notes = "parallel promo Hououmon"

class EX1_011 extends Card:
	func _init():
		name = "Gabumon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "EX1-011"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Reptile"
		power = 2000
		inherited_effect_text = "[When Attacking] [Once Per Turn] Reveal the top 3 cards of your deck. Add 1 Tamer card or 1 Digimon Card with [Gabumon] among them to your hand. Place the remaining cards at the bottom of your deck in any order."

class EX1_011_B extends Card:
	func _init():
		name = "Gabumon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "EX1-011 (B)"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Reptile"
		power = 2000
		inherited_effect_text = "[When Attacking] [Once Per Turn] Reveal the top 3 cards of your deck. Add 1 Tamer card or 1 Digimon Card with [Gabumon] among them to your hand. Place the remaining cards at the bottom of your deck in any order."
		is_parallel = true
		notes = "parallel promo"

class EX1_012 extends Card:
	func _init():
		name = "Gomamon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "EX1-012"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Sea Beast"
		power = 2000
		effect_text = "[On Play] Trash 1 digivolution card from the bottom of 1 of your opponent's Digimon."

class EX1_012_B extends Card:
	func _init():
		name = "Gomamon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "EX1-012 (B)"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Sea Beast"
		power = 2000
		effect_text = "[On Play] Trash 1 digivolution card from the bottom of 1 of your opponent's Digimon."
		is_parallel = true
		notes = "parallel promo"

class EX1_013 extends Card:
	func _init():
		name = "Veemon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "EX1-013"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Mini Dragon"
		power = 2000
		inherited_effect_text = "[Your Turn] [Once Per Turn] When this Digimon becomes unsuspended during your main phase, gain 1 memory."
		notes = "V-mon"

class EX1_014 extends Card:
	func _init():
		name = "ExVeemon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "EX1-014"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Mythical Beast"
		power = 4000
		effect_text = "[Jamming]"
		inherited_effect_text = "[Your Turn] While this Digimon has [Imperialdramon] or [Free], it gains [Jamming]."
		notes = "XV-mon"

class EX1_015 extends Card:
	func _init():
		name = "Garurumon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "EX1-015"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Beast"
		power = 5000
		inherited_effect_text = "[When Attacking] [Once Per Turn] You may play 1 [Matt Ishida] with a play cost of 3 or less from your hand without paying its memory cost."

class EX1_015_B extends Card:
	func _init():
		name = "Garurumon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "EX1-015 (B)"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Beast"
		power = 5000
		inherited_effect_text = "[When Attacking] [Once Per Turn] You may play 1 [Matt Ishida] with a play cost of 3 or less from your hand without paying its memory cost."
		is_parallel = true
		notes = "parallel promo"

class EX1_016 extends Card:
	func _init():
		name = "Ikkakumon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "EX1-016"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Sea Beast"
		power = 6000
		effect_text = "[Your Turn] This Digimon can also attack your opponent's unsuspended Digimon with no digivolution cards."

class EX1_017 extends Card:
	func _init():
		name = "WereGarurumon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "EX1-017"
		play_cost = 7
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Beastkin"
		power = 7000
		effect_text = "[When Digivolved] Trigger [Draw 1]"
		inherited_effect_text = "[When Attacking] [Once Per Turn] If you have 8 or more cards in your hand, gain 1 memory."

class EX1_018 extends Card:
	func _init():
		name = "Zudomon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "EX1-018"
		play_cost = 8
		level = 5
		stage_level = Stage.HYBRID
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Sea Beast"
		power = 8000
		effect_text = "[When Digivolved] Trash 1 digivolution card from the bottom of 1 of your opponent's Digimon.\n[Your Turn] This Digimon can also attack your opponent's unsuspended Digimon with no digivolution cards."

class EX1_019 extends Card:
	func _init():
		name = "Paildramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "EX1-019"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Dragonkin"
		power = 7000
		effect_text = "[When Digivolved] If a Digimon card with [Free] is in this Digimon's digivolution cards, unsuspend this Digimon."
		inherited_effect_text = "[Your Turn] While this Digimon has [Imperialdramon], it can't be blocked."

class EX1_019_B extends Card:
	func _init():
		name = "Paildramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "EX1-019 (B)"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Dragonkin"
		power = 7000
		effect_text = "[When Digivolved] If a Digimon card with [Free] is in this Digimon's digivolution cards, unsuspend this Digimon."
		inherited_effect_text = "[Your Turn] While this Digimon has [Imperialdramon], it can't be blocked."
		is_parallel = true
		notes = "parallel promo"

class EX1_020 extends Card:
	func _init():
		name = "Plesiomon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "EX1-020"
		play_cost = 11
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 2
		digivolve_level = 5
		digimon_type = "Plesiosaur"
		power = 11000
		effect_text = "[Your Turn] [Once Per Turn] When one of your opponent's digivolution cards is trashed, trigger [Draw 2].\n[Your Turn] This Digimon can also attack your opponent's unsuspended Digimon with no digivolution cards."

class EX1_021 extends Card:
	func _init():
		name = "MetalGarurumon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.SR
		id = "EX1-021"
		play_cost = 11
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Cyborg"
		power = 12000
		effect_text = "[When Digivolved] Gain 1 memory for every 4 cards in your hand.\n[When Attacking] If you have 8 or more cards in your hand and a Tamer in play, return 1 of your opponent's Digimon that has an [On Deletion] effect to the bottom of its owners deck. Trash all of the digivolution cards of that Digimon."

class EX1_021_B extends Card:
	func _init():
		name = "MetalGarurumon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.SR
		id = "EX1-021 (B)"
		play_cost = 11
		level = 6
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Cyborg"
		power = 12000
		effect_text = "[When Digivolved] Gain 1 memory for every 4 cards in your hand.\n[When Attacking] If you have 8 or more cards in your hand and a Tamer in play, return 1 of your opponent's Digimon that has an [On Deletion] effect to the bottom of its owners deck. Trash all of the digivolution cards of that Digimon."
		is_parallel = true
		notes = "parallel promo"

class EX1_022 extends Card:
	func _init():
		name = "Imperialdramon Dragon Mode"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.SR
		id = "EX1-022"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.GREEN
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Ancient Dragon"
		power = 11000
		effect_text = "[When Digivolved] If a Digimon card with [Free] is in this Digimon's digivolution cards, unsuspend this Digimon and suspend 1 of your opponent's Digimon.\n[Your Turn] For each color in this Digimon's digivolution cards, it gets +1000 DP."

class EX1_023 extends Card:
	func _init():
		name = "Elecmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "EX1-023"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Mammal"
		power = 2000
		inherited_effect_text = "[On Deletion] 1 of your opponent's Digimon gains [Security Attack -1] for the turn."

class EX1_024 extends Card:
	func _init():
		name = "Patamon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "EX1-024"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Mammal"
		power = 2000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon card with [Angel] among them to your hand. Place the remaining cards at the bottom of your deck in any order."

class EX1_024_B extends Card:
	func _init():
		name = "Patamon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "EX1-024 (B)"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Mammal"
		power = 2000
		effect_text = "[On Play] Reveal the top 4 cards of your deck. Add 1 Digimon card with [Angel] among them to your hand. Place the remaining cards at the bottom of your deck in any order."
		is_parallel = true
		notes = "parallel promo"

class EX1_025 extends Card:
	func _init():
		name = "Salamon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "EX1-025"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Mammal"
		power = 2000
		inherited_effect_text = "[When Attacking] [Once Per Turn] If you have 3 or more security cards, trigger [Draw 1]."
		notes = "Plotmon"

class EX1_026 extends Card:
	func _init():
		name = "Gatomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "EX1-026"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Holy Beast"
		power = 4000
		inherited_effect_text = "[When Attacking] [Once Per Turn] If you have 3 or more Security Cards, 1 of your opponent's Digimon gets -2000 DP for the turn."
		notes = "Tailmon"

class EX1_026_B extends Card:
	func _init():
		name = "Gatomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.U
		id = "EX1-026 (B)"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Holy Beast"
		power = 4000
		inherited_effect_text = "[When Attacking] [Once Per Turn] If you have 3 or more Security Cards, 1 of your opponent's Digimon gets -2000 DP for the turn."
		is_parallel = true
		notes = "parallel promo Tailmon"

class EX1_027 extends Card:
	func _init():
		name = "Leomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "EX1-027"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Beastkin"
		power = 5000
		effect_text = "[Security] At the end of the battle, if you have 3 security cards or fewer, trigger [Recovery +1]."

class EX1_028 extends Card:
	func _init():
		name = "Angemon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "EX1-028"
		play_cost = 6
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Angel"
		power = 6000
		inherited_effect_text = "[When Attacking] [Once Per Turn] If you have 3 or more security cards, this Digimon gets +1000 DP until the end of your opponent's next turn."

class EX1_029 extends Card:
	func _init():
		name = "MagnaAngemon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "EX1-029"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Archangel"
		power = 7000
		effect_text = "[When Attacking] While you have 3 or more security cards, this Digimon gets +4000 DP until the end of your opponent's next turn."
		inherited_effect_text = "[Your Turn] [Once Per Turn] When a card is added to your security stack, gain 1 memory."
		notes = "HolyAngemon"

class EX1_029_B extends Card:
	func _init():
		name = "MagnaAngemon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "EX1-029 (B)"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Archangel"
		power = 7000
		effect_text = "[When Attacking] While you have 3 or more security cards, this Digimon gets +4000 DP until the end of your opponent's next turn."
		inherited_effect_text = "[Your Turn] [Once Per Turn] When a card is added to your security stack, gain 1 memory."
		is_parallel = true
		notes = "parallel promo HolyAngemon"

class EX1_030 extends Card:
	func _init():
		name = "Angewomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "EX1-030"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Archangel"
		power = 7000
		effect_text = "[When Attacking] If you have 3 or more security cards, 1 of your opponent's Digimon and all of your opponent's security Digimon get -3000 DP for the turn."
		inherited_effect_text = "[Your Turn] [Once Per Turn] When a card is added to your security stack, 1 of your opponent's Digimon gets -2000 DP for the turn."

class EX1_030_B extends Card:
	func _init():
		name = "Angewomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "EX1-030 (B)"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Archangel"
		power = 7000
		effect_text = "[When Attacking] If you have 3 or more security cards, 1 of your opponent's Digimon and all of your opponent's security Digimon get -3000 DP for the turn."
		inherited_effect_text = "[Your Turn] [Once Per Turn] When a card is added to your security stack, 1 of your opponent's Digimon gets -2000 DP for the turn."
		is_parallel = true
		notes = "parallel promo"

class EX1_031 extends Card:
	func _init():
		name = "Seraphimon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "EX1-031"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Seraph"
		power = 12000
		effect_text = "[When Digivolved] Trigger [Recovery +1].\n[Opponent Turn] While this Digimon is suspended, all of your Security Digimon get +5000 DP."

class EX1_032 extends Card:
	func _init():
		name = "Magnadramon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "EX1-032"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Holy Dragon"
		power = 11000
		effect_text = "[When Digivolved] You may trash the top card of your security stack to unsuspend this Digimon.\n[When Attacking] [Once Per Turn] trigger, [Recovery +1]."
		notes = "Holydramon"

class EX1_033 extends Card:
	func _init():
		name = "Tentomon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "EX1-033"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Insectoid"
		power = 2000
		inherited_effect_text = "[When Attacking] The next time one of your Digimon would digivolve into a Digimon card with [Insectoid] this turn, reduce the memory cost of the digivolution by 1."

class EX1_033_B extends Card:
	func _init():
		name = "Tentomon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "EX1-033 (B)"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Insectoid"
		power = 2000
		inherited_effect_text = "[When Attacking] The next time one of your Digimon would digivolve into a Digimon card with [Insectoid] this turn, reduce the memory cost of the digivolution by 1."
		is_parallel = true
		notes = "parallel promo"

class EX1_034 extends Card:
	func _init():
		name = "Palmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "EX1-034"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Vegetation"
		power = 1000
		effect_text = "[On Deletion] Suspend 1 of your opponent's Digimon with 5000 DP or less."

class EX1_035 extends Card:
	func _init():
		name = "Kabuterimon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "EX1-035"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Insectoid"
		power = 5000
		effect_text = "[When Attacking] This Digimon can digivolve into a Digimon card with [Insectoid] in your hand for its digivolution cost."

class EX1_036 extends Card:
	func _init():
		name = "Togemon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "EX1-036"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Vegetation"
		power = 4000
		inherited_effect_text = "[Your Turn] [Once Per Turn] When one of your opponent's Digimon becomes suspended, this Digimon gets +2000 DP for the turn."

class EX1_037 extends Card:
	func _init():
		name = "Kuwagamon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "EX1-037"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Insectoid"
		power = 5000
		effect_text = "[Start of Your Turn] Suspend 1 of your opponent's Digimon with 3000 DP or less."
		inherited_effect_text = "[Your Turn] When this Digimon deletes one of your opponent's Digimon in battle and survives, 1 of your opponent's suspended Digimon doesn't unsuspend during their next unsuspend phase."

class EX1_038 extends Card:
	func _init():
		name = "Stingmon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "EX1-038"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.BLUE
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Insectoid"
		power = 5000
		effect_text = "[Piercing]"
		inherited_effect_text = "[Your Turn] While this Digimon has [Imperialdramon] or [Free], it gains [Piercing]."

class EX1_039 extends Card:
	func _init():
		name = "Lillymon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "EX1-039"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Fairy"
		power = 7000
		inherited_effect_text = "[Your Turn] [Once Per Turn] When one of your opponent's Digimon becomes suspended, this Digimon gains [Security Attack +1] for the turn."

class EX1_039_B extends Card:
	func _init():
		name = "Lillymon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "EX1-039 (B)"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Fairy"
		power = 7000
		inherited_effect_text = "[Your Turn] [Once Per Turn] When one of your opponent's Digimon becomes suspended, this Digimon gains [Security Attack +1] for the turn."
		is_parallel = true
		notes = "parallel promo"

class EX1_040 extends Card:
	func _init():
		name = "MegaKabuterimon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.R
		id = "EX1-040"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Insectoid"
		power = 7000
		inherited_effect_text = "[Your Turn] When this Digimon deletes an opponent's Digimon in battle and survives, gain 1 memory."
		notes = "AtlurKabuterimon"

class EX1_041 extends Card:
	func _init():
		name = "Dinobeemon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.C
		id = "EX1-041"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.BLUE
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Mutant"
		power = 7000
		effect_text = "[When Digivolved] If a Digimon card with [Free] is in this Digimon's digivolution cards, suspend 1 of your opponent's Digimon with 5000 DP or less."
		inherited_effect_text = "[Your Turn] When one of your Digimon with [Imperialdramon] deletes an opponent's Digimon in battle and survives, gain 1 memory."

class EX1_042 extends Card:
	func _init():
		name = "Rosemon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "EX1-042"
		play_cost = 11
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Fairy"
		power = 11000
		effect_text = "[Your Turn] his Digimon gets +1000 DP for each of your opponent's suspended Digimon.\n [When Attacking] Suspend 1 of your opponent's Digimon."

class EX1_043 extends Card:
	func _init():
		name = "HerculesKabuterimon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "EX1-043"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Insectoid"
		power = 12000
		effect_text = "[Your Turn] [Once Per Turn] When one of your Digimon with [Insectoid] deletes an opponent's Digimon in battle and survives, you may unsuspend this Digimon. \n[Your Turn]For each Digimon card with [Insectoid] in this Digimon's digivolution cards, it gets +1000 DP."
		notes = "HerakleKabuterimon"

class EX1_043_B extends Card:
	func _init():
		name = "HerculesKabuterimon"
		type = Type.DIGIMON
		color = ColorGroup.GREEN
		rarity = Rarity.U
		id = "EX1-043 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.GREEN
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Insectoid"
		power = 12000
		effect_text = "[Your Turn] [Once Per Turn] When one of your Digimon with [Insectoid] deletes an opponent's Digimon in battle and survives, you may unsuspend this Digimon. \n[Your Turn]For each Digimon card with [Insectoid] in this Digimon's digivolution cards, it gets +1000 DP."
		is_parallel = true
		notes = "parallel promo HerakleKabuterimon"

class EX1_044 extends Card:
	func _init():
		name = "Keramon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "EX1-044"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.UNKNOWN
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Unidentified"
		power = 2000
		inherited_effect_text = "[Your Turn] For each other Digimon you have in play with the same name as this Digimon, this Digimon gets +1000 DP."

class EX1_045 extends Card:
	func _init():
		name = "Hagurumon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "EX1-045"
		play_cost = 2
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Machine"
		power = 3000
		effect_text = "[On Play] You may trash 1 Digimon card with [Machine] in your hand to trigger [Draw 2]."

class EX1_046 extends Card:
	func _init():
		name = "Kurisarimon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "EX1-046"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.UNKNOWN
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Unidentified"
		power = 5000
		inherited_effect_text = "[Your Turn] [Once Per Turn] When one of your other Digimon with the same name as this Digimon is deleted, unsuspend this Digimon."
		notes = "Chrysalimon"

class EX1_047 extends Card:
	func _init():
		name = "Guardromon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "EX1-047"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Machine"
		power = 6000
		effect_text = "[Blocker].\n[Your Turn] This Digimon can't attack."
		inherited_effect_text = "[When Attacking] You may trash 1 Digimon card with [Machine] in your hand to trigger [Draw 2]."

class EX1_048 extends Card:
	func _init():
		name = "Andromon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "EX1-048"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Cyborg"
		power = 7000
		effect_text = "[When Digivolved] You may reveal the top 3 cards of your deck. Add 1 level 6 card with [Machine] among them to your hand. Trash the remaining cards."
		inherited_effect_text = "[Opponent Turn] While this Digimon has [Machine], it gains [Blocker]."

class EX1_049 extends Card:
	func _init():
		name = "MetalTyrannomon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "EX1-049"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Cyborg"
		power = 7000
		effect_text = "[When Digivolved] You may reveal the top 3 cards of your deck. Add 1 level 6 card with [Machine] among them to your hand. Trash the remaining cards."
		inherited_effect_text = "[Opponent Turn] While this Digimon has [Machine], it gains [Reboot]."

class EX1_050 extends Card:
	func _init():
		name = "MetalMamemon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.C
		id = "EX1-050"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Cyborg"
		power = 7000
		effect_text = "[When Digivolved] You may reveal the top 3 cards of your deck. Add 1 level 6 card with [Machine] among them to your hand. Trash the remaining cards."
		inherited_effect_text = "[When Attacking] While this Digimon has [Machine], delete 1 of your opponent's Digimon with a Play Cost of 5 or less."

class EX1_051 extends Card:
	func _init():
		name = "Infermon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "EX1-051"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.UNKNOWN
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Unidentified"
		power = 7000
		effect_text = "[Opponent Turn] [Once Per Turn] When an opponent's Digimon digivolves into a level 5 or higher Digimon, gain 1 memory."
		inherited_effect_text = "[All Turns] All of your other Digimon with the same name as this Digimon get +2000 DP."

class EX1_052 extends Card:
	func _init():
		name = "Etemon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "EX1-052"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Puppet"
		power = 7000
		effect_text = "[Your Turn] When this Digimon digivolves into a Digimon card with [Etemon] in your hand, reduce the memory cost of the digivolution by 1."
		inherited_effect_text = "[Your Turn]While this Digimon has [Etemon] , it gains [Jamming]."

class EX1_053 extends Card:
	func _init():
		name = "MetalEtemon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "EX1-053"
		play_cost = 11
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Cyborg"
		power = 10000
		effect_text = "[Your Turn] For each Digimon card with [Etemon] in your trash, this Digimon gets +1000 DP.\n[On Deletion] trigger [De-Digivolve 1]."

class EX1_054 extends Card:
	func _init():
		name = "Boltmon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.U
		id = "EX1-054"
		play_cost = 10
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Cyborg"
		power = 12000
		effect_text = "[Reboot]\n[When Digivolved] Trigger [De-Digivolve 1]."

class EX1_055 extends Card:
	func _init():
		name = "Tapirmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "EX1-055"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Holy Beast"
		power = 2000
		inherited_effect_text = "[Your Turn] [Once Per Turn] When one of your other Digimon is deleted, trigger [Draw 1]."
		notes = "Bakumon"

class EX1_056 extends Card:
	func _init():
		name = "DemiDevimon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "EX1-056"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Evil"
		power = 2000
		effect_text = "[Retaliation]\n[Your Turn] While you don't have a Digimon with [Myotismon] in play, this Digimon can't attack your opponent's Digimon."
		notes = "PicoDevimon"

class EX1_057 extends Card:
	func _init():
		name = "Wizardmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "EX1-057"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Wizard"
		power = 3000
		effect_text = "[Retaliation]"
		inherited_effect_text = "[Your Turn] All of your Digimon with [Retaliation] gain [Rush]."
		notes = "Wizarmon"

class EX1_058 extends Card:
	func _init():
		name = "Devimon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "EX1-058"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Fallen Angel"
		power = 6000
		inherited_effect_text = "[On Deletion] Return 1 purple level 4 or lower Digimon card from your trash to your hand."

class EX1_059 extends Card:
	func _init():
		name = "Ogremon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.R
		id = "EX1-059"
		play_cost = 6
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Demon"
		power = 5000
		effect_text = "[When Attacking] You may trash 1 card in your hand to have this Digimon gain [Security Attack +1] for the turn."
		inherited_effect_text = "[When Attacking] You may trash 1 card in your hand to have this Digimon get +2000 DP for the turn."

class EX1_060 extends Card:
	func _init():
		name = "LadyDevimon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "EX1-060"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Fallen Angel"
		power = 7000
		effect_text = "[When Digivolved] You may trash the top 3 cards of your deck."
		inherited_effect_text = "[Your Turn] [Once Per Turn] When you play a Digimon from your trash, gain 1 memory."

class EX1_061 extends Card:
	func _init():
		name = "Myotismon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.R
		id = "EX1-061"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Undead"
		power = 7000
		effect_text = "[Your Turn] When this Digimon digivolves into a Digimon with [Myotismon] from your hand, reduce the memory cost of the digivolution by 1."
		inherited_effect_text = "While this Digimon has [Myotismon], all your Digimon with [Retaliation] can attack your opponent's unsuspended level 4 or lower Digimon."
		notes = "Vamdemon"

class EX1_062 extends Card:
	func _init():
		name = "SkullGreymon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.R
		id = "EX1-062"
		play_cost = 8
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.RED
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Undead"
		power = 8000
		effect_text = "[Security Attack +1]\n[End of Attack] Delete this Digimon.\n[On Deletion] You may play 1 [Agumon] from your trash suspended without paying its memory cost."

class EX1_063 extends Card:
	func _init():
		name = "VenomMyotismon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.SR
		id = "EX1-063"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Dark Animal"
		power = 12000
		effect_text = "[Retaliation].\n[When Attacking] [Once Per Turn] You may play 1 purple level 4 or lower Digimon card with [Retaliation] from your trash without paying its memory cost. Any [On Play] effects on Digimon played with this effect don't activate."
		notes = "VenomVamdemon"

class EX1_063_B extends Card:
	func _init():
		name = "VenomMyotismon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.SR
		id = "EX1-063 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Dark Animal"
		power = 12000
		effect_text = "[Retaliation].\n[When Attacking] [Once Per Turn] You may play 1 purple level 4 or lower Digimon card with [Retaliation] from your trash without paying its memory cost. Any [On Play] effects on Digimon played with this effect don't activate."
		is_parallel = true
		notes = "parallel promo VenomVamdemon"

class EX1_064 extends Card:
	func _init():
		name = "Piedmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "EX1-064"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Wizard"
		power = 11000
		effect_text = "[On Play] Delete 4 of your opponent's unsuspended level 4 or lower Digimon.\n[Your Turn] [Once Per Turn] When one of your opponent's Digimon is deleted, trigger [Draw 1]."
		notes = "Piemon"

class EX1_065 extends Card:
	func _init():
		name = "Diaboromon"
		type = Type.DIGIMON
		color = ColorGroup.WHITE
		rarity = Rarity.SR
		id = "EX1-065"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.UNKNOWN
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Unidentified"
		power = 11000
		effect_text = "[Security] At the end of the battle, you may play 1 [Diaboromon] Token\n[Opponent Turn] All of your [Diaboromon] gain [Blocker]."
		notes = "Diablomon"

class EX1_065_B extends Card:
	func _init():
		name = "Diaboromon"
		type = Type.DIGIMON
		color = ColorGroup.WHITE
		rarity = Rarity.SR
		id = "EX1-065 (B)"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.UNKNOWN
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Unidentified"
		power = 11000
		effect_text = "[Security] At the end of the battle, you may play 1 [Diaboromon] Token\n[Opponent Turn] All of your [Diaboromon] gain [Blocker]."
		is_parallel = true
		notes = "parallel promo Diablomon"

class EX1_066 extends Card:
	func _init():
		name = "Analog Youth"
		type = Type.TAMER
		color = ColorGroup.WHITE
		rarity = Rarity.R
		id = "EX1-066"
		play_cost = 2
		effect_text = "[On Play] Reveal the top 3 cards of your deck. Add 1 Digimon card among them to your hand. Trash the remaining cards.\n[All Turns] When one of your level 5 or higher Digimon with digivolution cards is deleted, you may suspend this Tamer. If you do, gain 1 memory, then hatch 1 Digi-Egg card to an empty space in your Breeding Area."
		sec_effect_text = "[Security] Play this card without paying its memory cost."

class EX1_066_B extends Card:
	func _init():
		name = "Analog Youth"
		type = Type.TAMER
		color = ColorGroup.WHITE
		rarity = Rarity.R
		id = "EX1-066 (B)"
		play_cost = 2
		effect_text = "[On Play] Reveal the top 3 cards of your deck. Add 1 Digimon card among them to your hand. Trash the remaining cards.\n[All Turns] When one of your level 5 or higher Digimon with digivolution cards is deleted, you may suspend this Tamer. If you do, gain 1 memory, then hatch 1 Digi-Egg card to an empty space in your Breeding Area."
		sec_effect_text = "[Security] Play this card without paying its memory cost."
		is_parallel = true
		notes = "parallel promo"

class EX1_067 extends Card:
	func _init():
		name = "Baptism by Fire!"
		type = Type.OPTION
		color = ColorGroup.RED
		rarity = Rarity.R
		id = "EX1-067"
		play_cost = 3
		effect_text = "[Main] Delete 1 of your opponent's Digimon with 6000 DP or less and [Blocker]."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class EX1_068 extends Card:
	func _init():
		name = "Ice Wall!"
		type = Type.OPTION
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "EX1-068"
		play_cost = 1
		effect_text = "[Main] All of your opponent's Digimon gain \"[When Attacking] lose 2 memory\" until the end of your opponent's next turn."
		sec_effect_text = "[Security] Gain 2 memory."

class EX1_069 extends Card:
	func _init():
		name = "Ultimate Connection!"
		type = Type.OPTION
		color = ColorGroup.BLACK
		rarity = Rarity.R
		id = "EX1-069"
		play_cost = 1
		effect_text = "[Main] You may trash 1 level 5 Digimon card with [Cyborg] in your hand to gain 2 memory and trigger [Draw 1]."
		sec_effect_text = "[Security] Activate this card's [Main] effect."

class EX1_070 extends Card:
	func _init():
		name = "Fight for Your Pride!"
		type = Type.OPTION
		color = ColorGroup.PURPLE
		rarity = Rarity.R
		id = "EX1-070"
		play_cost = 4
		effect_text = "[Main] Play 1 purple level 4 or lower Digimon card from your trash without paying its memory cost. Then, if you have a Digimon with [Myotismon] in play, 1 of your Digimon gains [Blocker] until the end of your opponent's next turn."
		sec_effect_text = "[Security] Play 1 purple level 4 or lower Digimon card from your trash without paying its memory cost."

class EX1_071 extends Card:
	func _init():
		name = "Win Rate: 60%!"
		type = Type.OPTION
		color = ColorGroup.WHITE
		rarity = Rarity.R
		id = "EX1-071"
		play_cost = 2
		effect_text = "If you have a Tamer in play, you may use this Option card without meeting its color requirements.\n[Main] The next time one of your Digimon digivolves this turn, you may trash 1 Digimon card in your hand of the same color as the digivolving Digimon to reduce the memory cost of the digivolution by 4."
		sec_effect_text = "[Security] Add this card to its owner's hand."

class EX1_072 extends Card:
	func _init():
		name = "Emergency Program Shutdown!"
		type = Type.OPTION
		color = ColorGroup.WHITE
		rarity = Rarity.R
		id = "EX1-072"
		play_cost = 3
		effect_text = "[Main] Your opponent can't use Option cards until the end of their next turn."
		sec_effect_text = "[Security] Your opponent can't use Option cards this turn. Then, add this card to its owner's hand."

class EX1_073 extends Card:
	func _init():
		name = "Machinedramon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.SEC
		id = "EX1-073"
		play_cost = 10
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.RED
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Machine"
		power = 11000
		effect_text = "[On Play] You may place up to 5 red and/or black level 5 Digimon cards with [Cyborg] and different card numbers from your hand and/or trash in this card's digivolution cards to gain 1 memory for each card placed.\n[All Turns] This Digimon's DP can't be reduced.\n[All Turns] When this Digimon would be deleted, you may trash 2 level 5 Digimon cards in this Digimon's digivolution cards to prevent this Digimon from being deleted."
		notes = "Mugendramon"

class EX1_073_B extends Card:
	func _init():
		name = "Machinedramon"
		type = Type.DIGIMON
		color = ColorGroup.BLACK
		rarity = Rarity.SEC
		id = "EX1-073 (B)"
		play_cost = 10
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.BLACK
		digivolve_cost = 3
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.RED
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Machine"
		power = 11000
		effect_text = "[On Play] You may place up to 5 red and/or black level 5 Digimon cards with [Cyborg] and different card numbers from your hand and/or trash in this card's digivolution cards to gain 1 memory for each card placed.\n[All Turns] This Digimon's DP can't be reduced.\n[All Turns] When this Digimon would be deleted, you may trash 2 level 5 Digimon cards in this Digimon's digivolution cards to prevent this Digimon from being deleted."
		is_parallel = true
		notes = "parallel promo Mugendramon"

