# Content autogenerated. Data from digimoncardgame.fandom.com

static func register_cards():

	CardDB.register_booster("ST-10", "ST-10: Parallel World Tactician")
	CardDB.add_card(ST10_01.new())
	CardDB.add_card(ST10_02.new())
	CardDB.add_card(ST10_03.new())
	CardDB.add_card(ST10_04.new())
	CardDB.add_card(ST10_05.new())
	CardDB.add_card(ST10_06.new())
	CardDB.add_card(ST10_06_B.new())
	CardDB.add_card(ST10_07.new())
	CardDB.add_card(ST10_08.new())
	CardDB.add_card(ST10_09.new())
	CardDB.add_card(ST10_10.new())
	CardDB.add_card(ST10_11.new())
	CardDB.add_card(ST10_12.new())
	CardDB.add_card(ST10_13.new())
	CardDB.add_card(ST10_14.new())
	CardDB.add_card(ST10_15.new())

class ST10_01 extends Card:
	func _init():
		name = "Nyaromon"
		type = Type.DIGITAMA
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "ST10-01"
		level = 2
		stage_level = Stage.IN_TRAINING
		digimon_type = "Lesser"
		inherited_effect_text = "[When Attacking] If you have a Yellow Digimon in play, [Draw 1]. If you do, trash 1 card in your hand."

class ST10_02 extends Card:
	func _init():
		name = "Salamon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "ST10-02"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.PURPLE
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Mammal"
		power = 2000
		inherited_effect_text = "[End of Your Turn] You can DNA Digivolve this Digimon and your other Digimon in play into a Digimon card in your hand by paying its DNA Digivolution cost."
		notes = "Plotmon"

class ST10_03 extends Card:
	func _init():
		name = "Lopmon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.C
		id = "ST10-03"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.PURPLE
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Beast"
		power = 4000

class ST10_04 extends Card:
	func _init():
		name = "Gatomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "ST10-04"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 3
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.PURPLE
		digivolve_cost_2 = 3
		digivolve_level_2 = 3
		digimon_type = "Holy Beast"
		power = 4000
		effect_text = "[On Play] Reveal the top 3 cards of your deck. You may add 1 Purple and 1 Yellow Digimon card among them to your hand. Return the remaining cards to the bottom of your deck in any order.\n[Your Turn] When this Digimon digivolves into a Digimon with [Archangel], reduce the digivolution cost by 2."
		inherited_effect_text = "[End of Your Turn] You can DNA Digivolve this Digimon and your other Digimon in play into a Digimon card in your hand by paying its DNA Digivolution cost."
		notes = "Tailmon"

class ST10_05 extends Card:
	func _init():
		name = "Angewomon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "ST10-05"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 3
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.PURPLE
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Archangel"
		power = 6000
		effect_text = "[On Play] 1 of your opponent's Digimon gains [Security Attack -2] until the end of your opponent's next turn."
		inherited_effect_text = "[Your Turn] While you have a Purple Digimon in play, this Digimon gains [Security Attack +1]."

class ST10_06 extends Card:
	func _init():
		name = "Mastemon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "ST10-06"
		play_cost = 13
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 5
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.PURPLE
		digivolve_cost_2 = 5
		digivolve_level_2 = 5
		digimon_type = "Angel"
		power = 13000
		effect_text = "<DNA Digivolve: [Yellow Level 5] + [Purple Level 5]: [0]>\n[When Digivolved] Place 1 yellow or purple Digimon card from your trash on top of your security stack face down. When DNA digivolving, you may search your security stack for 1 level 5 or lower Digimon card and play it without paying its memory cost. Then, shuffle your security stack.\n[All Turns] When you play another Digimon using an effect, delete 1 of your opponent's Digimon whose level is less than or equal to the played Digimon's level."

class ST10_06_B extends Card:
	func _init():
		name = "Mastemon"
		type = Type.DIGIMON
		color = ColorGroup.YELLOW
		rarity = Rarity.SR
		id = "ST10-06 (B)"
		play_cost = 13
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.YELLOW
		digivolve_cost = 5
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.PURPLE
		digivolve_cost_2 = 5
		digivolve_level_2 = 5
		digimon_type = "Angel"
		power = 13000
		effect_text = "<DNA Digivolve: [Yellow Level 5] + [Purple Level 5]: [0]>\n[When Digivolved] Place 1 yellow or purple Digimon card from your trash on top of your security stack face down. When DNA digivolving, you may search your security stack for 1 level 5 or lower Digimon card and play it without paying its memory cost. Then, shuffle your security stack.\n[All Turns] When you play another Digimon using an effect, delete 1 of your opponent's Digimon whose level is less than or equal to the played Digimon's level."
		is_parallel = true
		notes = "parallel promo"

class ST10_07 extends Card:
	func _init():
		name = "Ghostmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "ST10-07"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Ghost"
		power = 2000
		effect_text = "[Opponent Turn] While you have a yellow Digimon in play, this Digimon gains [Blocker]."

class ST10_08 extends Card:
	func _init():
		name = "Tsukaimon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "ST10-08"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 0
		digivolve_level = 2
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 0
		digivolve_level_2 = 2
		digimon_type = "Mammal"
		power = 2000
		effect_text = "[On Play] Reveal the top 3 cards of your deck. Add 1 [Angel] among them to your hand. Return the remaining cards to the bottom of your deck in any order."

class ST10_09 extends Card:
	func _init():
		name = "Witchmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "ST10-09"
		play_cost = 6
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Wizard"
		power = 4000
		effect_text = "[Security] At the end of battle, play this card without paying its cost.\n[On Play] Return 1 purple level 5 or lower Digimon card from your trash to your hand."

class ST10_10 extends Card:
	func _init():
		name = "Wizardmon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "ST10-10"
		play_cost = 5
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 2
		digivolve_level = 3
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 2
		digivolve_level_2 = 3
		digimon_type = "Wizard"
		power = 6000

class ST10_11 extends Card:
	func _init():
		name = "Bastemon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.C
		id = "ST10-11"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Beastkin"
		power = 7000
		effect_text = "[On Play] Delete 1 of your opponent's level 3 Digimon."

class ST10_12 extends Card:
	func _init():
		name = "LadyDevimon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.R
		id = "ST10-12"
		play_cost = 6
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 4
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 3
		digivolve_level_2 = 4
		digimon_type = "Fallen Angel"
		power = 6000
		effect_text = "[When Digivolved] You may trash 1 card in your hand to reveal the top 3 cards of your deck. You can add 1 Yellow and 1 Purple Digimon with [Angel] among them to your hand. Place the remaining cards at the bottom of your deck in any order."
		inherited_effect_text = "[Your Turn] All of your Yellow Digimon gain [Retaliation]."

class ST10_13 extends Card:
	func _init():
		name = "Junomon"
		type = Type.DIGIMON
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "ST10-13"
		play_cost = 11
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VIRUS
		digivolve_color = ColorGroup.PURPLE
		digivolve_cost = 3
		digivolve_level = 5
		digivolve_color_2 = ColorGroup.YELLOW
		digivolve_cost_2 = 3
		digivolve_level_2 = 5
		digimon_type = "Shaman"
		power = 11000
		effect_text = "[Retaliation]\n[When Digivolved] Trash top 3 cards of your deck. Then, return 1 Digimon card from your trash to your hand."

class ST10_14 extends Card:
	func _init():
		name = "Chaos Degradation"
		type = Type.OPTION
		color = ColorGroup.YELLOW
		rarity = Rarity.R
		id = "ST10-14"
		play_cost = 8
		effect_text = "[Main] Place 1 of your opponent's Digimon at the top or the bottom of their security stack face down. If you did, trash the top card of your opponent's security stack."
		sec_effect_text = "[Security] You may place 1 of your opponent's Digimon at the top or bottom of their security stack face down."
		notes = "Chaos Degrade"

class ST10_15 extends Card:
	func _init():
		name = "Darkness Wave"
		type = Type.OPTION
		color = ColorGroup.PURPLE
		rarity = Rarity.U
		id = "ST10-15"
		play_cost = 1
		effect_text = "[Main] Trash the top 3 cards of your deck. Then, if you have a yellow Digimon in play, return 1 yellow or purple Digimon card from your trash to your hand"
		sec_effect_text = "[Security] Activate this card's [Main] effect."

