# Content autogenerated. Data from digimoncardgame.fandom.com

static func register_cards():

	CardDB.register_booster("ST-8", "ST-8: UlforceVeedramon")
	CardDB.add_card(ST8_01.new())
	CardDB.add_card(ST8_02.new())
	CardDB.add_card(ST8_03.new())
	CardDB.add_card(ST8_04.new())
	CardDB.add_card(ST8_05.new())
	CardDB.add_card(ST8_06.new())
	CardDB.add_card(ST8_07.new())
	CardDB.add_card(ST8_08.new())
	CardDB.add_card(ST8_09.new())
	CardDB.add_card(ST8_10.new())
	CardDB.add_card(ST8_11.new())
	CardDB.add_card(ST8_12.new())

class ST8_01 extends Card:
	func _init():
		name = "DemiVeemon"
		type = Type.DIGITAMA
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "ST8-01"
		level = 2
		stage_level = Stage.IN_TRAINING
		digimon_type = "Baby Dragon"
		inherited_effect_text = "[Your Turn] If you have 8 or more cards in your hand,  this Digimon gets +1000 DP."
		notes = "Chibimon"

class ST8_02 extends Card:
	func _init():
		name = "Gabumon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "ST8-02"
		play_cost = 3
		level = 3
		stage_level = Stage.HYBRID
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Reptile"
		power = 2000
		inherited_effect_text = "[All Turns] While you have 8 or more cards in your hand, this Digimon gets +1000 DP."

class ST8_03 extends Card:
	func _init():
		name = "Dracomon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.C
		id = "ST8-03"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.DATA
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Dragon"
		power = 2000
		effect_text = "[On Play] Reveal the top 3 cards from your Deck. Add 1 Digimon Card with [Dramon] to your hand. Place the remaining cards at the bottom of your deck in any order."

class ST8_04 extends Card:
	func _init():
		name = "Veemon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.SR
		id = "ST8-04"
		play_cost = 3
		level = 3
		stage_level = Stage.ROOKIE
		attribute = Attribute.FREE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 0
		digivolve_level = 2
		digimon_type = "Mini Dragon"
		power = 2000
		effect_text = "[Your Turn] While your opponent has a level 6 or higher Digimon in play, this Digimon can digivolve into a [UlforceVeedramon] card in your hand for a memory cost of 4, ignoring that card's digivolution requirements."
		inherited_effect_text = "[When Attacking] If you have 7 of fewer cards in your hand, trigger [Draw 1]."
		notes = "V-mon"

class ST8_05 extends Card:
	func _init():
		name = "Veedramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "ST8-05"
		play_cost = 4
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Mythical Dragon"
		power = 5000
		inherited_effect_text = "[When Attacking] If you have 8 or more cards in your hand, return 1 of your opponent's level 3 Digimon to their hand. (Trash all the digivolution cards of that Digimon)."

class ST8_06 extends Card:
	func _init():
		name = "Coredramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "ST8-06"
		play_cost = 6
		level = 4
		stage_level = Stage.CHAMPION
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 2
		digivolve_level = 3
		digimon_type = "Dragon"
		power = 5000
		effect_text = "[Security] At the end of the battle, play this card without paying its memory cost.\n[On Play] Trigger [Draw 2]."

class ST8_07 extends Card:
	func _init():
		name = "Wingdramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "ST8-07"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Sky Dragon"
		power = 7000
		effect_text = "[Blocker]."

class ST8_08 extends Card:
	func _init():
		name = "AeroVeedramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "ST8-08"
		play_cost = 7
		level = 5
		stage_level = Stage.ULTIMATE
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 4
		digimon_type = "Holy Dragon"
		power = 7000
		effect_text = "[Jamming]"
		inherited_effect_text = "[Your Turn] While you have 8 or more cards in your hand this Digimon gains [Security Attack +1]."
		notes = "AeroV-dramon"

class ST8_09 extends Card:
	func _init():
		name = "Slayerdramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.R
		id = "ST8-09"
		play_cost = 11
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 3
		digivolve_level = 5
		digimon_type = "Dragonkin"
		power = 10000
		effect_text = "[When Digivolved] This Digimon gains [Security Attack +1] for the turn.\n[Your Turn] This Digimon can't be blocked by your opponent's Digimon."

class ST8_10 extends Card:
	func _init():
		name = "UlforceVeedramon"
		type = Type.DIGIMON
		color = ColorGroup.BLUE
		rarity = Rarity.SR
		id = "ST8-10"
		play_cost = 12
		level = 6
		stage_level = Stage.MEGA
		attribute = Attribute.VACCINE
		digivolve_color = ColorGroup.BLUE
		digivolve_cost = 4
		digivolve_level = 5
		digimon_type = "Holy Warrior"
		power = 12000
		effect_text = "[When Digivolved] Return 1 level 4 or lower Digimon to it's owner's hand. Trash all of the digivolution cards of that Digimon.\n[When Attacking] [Once Per Turn] If you have 8 or more cards in your hand, unsuspend this Digimon."
		notes = "UlforceV-dramon"

class ST8_11 extends Card:
	func _init():
		name = "Victory Sword"
		type = Type.OPTION
		color = ColorGroup.BLUE
		rarity = Rarity.U
		id = "ST8-11"
		play_cost = 3
		effect_text = "[Main] Unsuspend 1 of your Blue Digimon."
		sec_effect_text = "[Security] Add this card to your hand."
		notes = "Ulforce Saber"

class ST8_12 extends Card:
	func _init():
		name = "V-Wing Blade"
		type = Type.OPTION
		color = ColorGroup.BLUE
		rarity = ""
		id = "ST8-12"
		play_cost = 6
		effect_text = "[Main] Return 1 of your opponent's level 6 or lower Digimon to it's owner's hand. (Trash all of the digivolution cards of that Digimon.)"
		sec_effect_text = "[Security] Activate this card's [Main] effect."

